<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double"/>
  </ecore:EPackage>
  <ecore:EPackage name="Bugzilla">
    <eClassifiers xsi:type="ecore:EEnum" name="ErrorType">
      <eLiterals name="et_null"/>
      <eLiterals name="et_NotFound"/>
      <eLiterals name="et_NotPermitted"/>
      <eLiterals name="et_InvalidBugId"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SeverityType">
      <eLiterals name="st_null"/>
      <eLiterals name="st_blocker"/>
      <eLiterals name="st_critical"/>
      <eLiterals name="st_major"/>
      <eLiterals name="st_normal"/>
      <eLiterals name="st_minor"/>
      <eLiterals name="st_trivial"/>
      <eLiterals name="st_enhancement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="StatusType">
      <eLiterals name="st_null"/>
      <eLiterals name="st_UNCONFIRMED"/>
      <eLiterals name="st_NEW"/>
      <eLiterals name="st_ASSIGNED"/>
      <eLiterals name="st_REOPENED"/>
      <eLiterals name="st_RESOLVED"/>
      <eLiterals name="st_VERIFIED"/>
      <eLiterals name="st_CLOSED"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OperatingSystemType">
      <eLiterals name="ost_null"/>
      <eLiterals name="ost_all"/>
      <eLiterals name="ost_Windows 3.1"/>
      <eLiterals name="ost_Windows 95"/>
      <eLiterals name="ost_Windows 98"/>
      <eLiterals name="ost_Windows ME"/>
      <eLiterals name="ost_Windows 2000"/>
      <eLiterals name="ost_Windows NT"/>
      <eLiterals name="ost_Windows XP"/>
      <eLiterals name="ost_Windows Server 2003"/>
      <eLiterals name="ost_MacSystem 7"/>
      <eLiterals name="ost_MacSystem 7.5"/>
      <eLiterals name="ost_MacSystem 7.6.1"/>
      <eLiterals name="ost_MacSystem 8.0"/>
      <eLiterals name="ost_MacSystem 8.5"/>
      <eLiterals name="ost_MacSystem 8.6"/>
      <eLiterals name="ost_MacSystem 9.x"/>
      <eLiterals name="ost_Mac OS X 10.0"/>
      <eLiterals name="ost_Mac OS X 10.1"/>
      <eLiterals name="ost_Mac OS X 10.2"/>
      <eLiterals name="ost_Mac OS X 10.3"/>
      <eLiterals name="ost_Linux"/>
      <eLiterals name="ost_BDS/OS"/>
      <eLiterals name="ost_FreeBSD"/>
      <eLiterals name="ost_NetBSD"/>
      <eLiterals name="ost_OpenBSD"/>
      <eLiterals name="ost_AIX"/>
      <eLiterals name="ost_BeOS"/>
      <eLiterals name="ost_HP-UX"/>
      <eLiterals name="ost_IRIX"/>
      <eLiterals name="ost_Neutrino"/>
      <eLiterals name="ost_OpenVMS"/>
      <eLiterals name="ost_OS/2"/>
      <eLiterals name="ost_OSF/1"/>
      <eLiterals name="ost_Solaris"/>
      <eLiterals name="ost_SunOS"/>
      <eLiterals name="ost_other"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PriorityType">
      <eLiterals name="pt_null"/>
      <eLiterals name="pt_P1"/>
      <eLiterals name="pt_P2"/>
      <eLiterals name="pt_P3"/>
      <eLiterals name="pt_P4"/>
      <eLiterals name="pt_P5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ReportedPlatformType">
      <eLiterals name="rpt_null"/>
      <eLiterals name="rpt_all"/>
      <eLiterals name="rpt_DEC"/>
      <eLiterals name="rpt_HP"/>
      <eLiterals name="rpt_Macintosh"/>
      <eLiterals name="rpt_PC"/>
      <eLiterals name="rpt_SGI"/>
      <eLiterals name="rpt_Sun"/>
      <eLiterals name="rpt_other"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ResolutionType">
      <eLiterals name="rt_null"/>
      <eLiterals name="rt_FIXED"/>
      <eLiterals name="rt_INVALID"/>
      <eLiterals name="rt_WONTFIX"/>
      <eLiterals name="rt_LATER"/>
      <eLiterals name="rt_REMIND"/>
      <eLiterals name="rt_DUPLICATE"/>
      <eLiterals name="rt_WORKSFORME"/>
      <eLiterals name="rt_MOVED"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BugzillaRoot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlbase" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintainer" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporter" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bugs" lowerBound="1" upperBound="-1" eType="/1/Bug" containment="true" eOpposite="/1/Bug/bug_bugzillaRoot"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bug">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bug_bugzillaRoot" ordered="false" lowerBound="1" eType="/1/BugzillaRoot" eOpposite="/1/BugzillaRoot/bugs"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" ordered="false" eType="/1/ErrorType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_id" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporter" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlbase" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_status" ordered="false" lowerBound="1" eType="/1/StatusType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" ordered="false" eType="/1/ResolutionType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="product" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" ordered="false" lowerBound="1" eType="/1/PriorityType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rep_platform" ordered="false" lowerBound="1" eType="/1/ReportedPlatformType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assigned_to" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delta_ts" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reporter" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_milestone" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_severity" ordered="false" lowerBound="1" eType="/1/SeverityType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creation_ts" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qa_contact" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status_whiteboard" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="op_sys" ordered="false" lowerBound="1" eType="/1/OperatingSystemType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_file_loc" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="short_desc" ordered="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keywords" upperBound="-1" eType="/1/Keywords" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependson" upperBound="-1" eType="/1/Dependson" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1" eType="/1/Blocks" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cc" upperBound="-1" eType="/1/Cc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="long_desc" ordered="false" eType="/1/LongDesc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachment" upperBound="-1" eType="/1/Attachment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Keywords" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Dependson" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Blocks" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cc" eSuperTypes="/1/StringElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="LongDesc">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bug_when" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="thetext" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attachment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
