<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="XSLT">
    <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" ordered="false" eType="/0/ElementNode" eOpposite="/0/ElementNode/nodes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementNode" eSuperTypes="/0/Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1" eType="/0/Node" containment="true" eOpposite="/0/Node/parentNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeNode" eSuperTypes="/0/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="RootNode" eSuperTypes="/0/ElementNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="document" ordered="false" lowerBound="1" eType="/0/Document"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextNode" eSuperTypes="/0/ElementNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSLTNode" abstract="true" eSuperTypes="/0/ElementNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSLTRootNode" eSuperTypes="/0/RootNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="Document">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentName" ordered="false" lowerBound="1" eType="/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="document" ordered="false" lowerBound="1" eType="/0/Document" eOpposite="/0/Document/document"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ApplyTemplates" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="select" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="test" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="match" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueOf" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="select" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="When" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="test" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Choose" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="when" ordered="false" lowerBound="1" eType="/0/When"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="otherwise" ordered="false" lowerBound="1" eType="/0/Otherwise"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Otherwise" eSuperTypes="/0/XSLTNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sort" eSuperTypes="/0/XSLTNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="select" ordered="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
</xmi:XMI>
