<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PetriNetMM1" nsURI="PetriNetMM1" nsPrefix="PetriNetMM1">
    <eClassifiers xsi:type="ecore:EClass" name="PetriNetModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
          upperBound="-1" eType="#/0/PetriNetModelElement" containment="true" eOpposite="#/0/PetriNetModelElement/modelContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PetriNetModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelContainer" ordered="false"
          lowerBound="1" eType="#/0/PetriNetModel" eOpposite="#/0/PetriNetModel/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Net" eSuperTypes="#/0/PetriNetModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="place" ordered="false"
          upperBound="-1" eType="#/0/Place" containment="true" eOpposite="#/0/Place/net"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transition" ordered="false"
          upperBound="-1" eType="#/0/Transition" containment="true" eOpposite="#/0/Transition/net"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Place">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="net" ordered="false"
          lowerBound="1" eType="#/0/Net" eOpposite="#/0/Net/place"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" ordered="false"
          upperBound="-1" eType="#/0/PTArc" containment="true" eOpposite="#/0/PTArc/src"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" ordered="false" upperBound="-1"
          eType="#/0/TPArc" containment="true" eOpposite="#/0/TPArc/dst"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="net" ordered="false"
          lowerBound="1" eType="#/0/Net" eOpposite="#/0/Net/transition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" ordered="false" lowerBound="1"
          upperBound="-1" eType="#/0/PTArc" containment="true" eOpposite="#/0/PTArc/dst"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/0/TPArc" containment="true" eOpposite="#/0/TPArc/src"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PTArc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false"
          lowerBound="1" eType="#/0/Place" eOpposite="#/0/Place/out"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dst" ordered="false"
          upperBound="-1" eType="#/0/Transition" eOpposite="#/0/Transition/in"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TPArc">
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" ordered="false"
          lowerBound="1" eType="#/0/Transition" eOpposite="#/0/Transition/out"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dst" ordered="false"
          upperBound="-1" eType="#/0/Place" eOpposite="#/0/Place/in"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
</xmi:XMI>
