<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Enum">
    <eClassifiers xsi:type="ecore:EEnum" name="Direction">
      <eLiterals name="inout"/>
      <eLiterals name="in"/>
      <eLiterals name="out"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SIPMethod">
      <eLiterals name="ACK"/>
      <eLiterals name="BYE"/>
      <eLiterals name="CANCEL"/>
      <eLiterals name="INVITE"/>
      <eLiterals name="NOTIFY"/>
      <eLiterals name="OPTIONS"/>
      <eLiterals name="REACK"/>
      <eLiterals name="REGISTER"/>
      <eLiterals name="REINVITE"/>
      <eLiterals name="REREGISTER"/>
      <eLiterals name="RESUBSCRIBE"/>
      <eLiterals name="SUBSCRIBE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ControlMethod">
      <eLiterals name="deploy"/>
      <eLiterals name="undeploy"/>
      <eLiterals name="uninvite"/>
      <eLiterals name="unregister"/>
      <eLiterals name="unsubscribe"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
      <eLiterals name="void"/>
      <eLiterals name="bool"/>
      <eLiterals name="int"/>
      <eLiterals name="request"/>
      <eLiterals name="response"/>
      <eLiterals name="string"/>
      <eLiterals name="time"/>
      <eLiterals name="uri"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Modifier">
      <eLiterals name="LIFO"/>
      <eLiterals name="FIFO"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FunctionLocation">
      <eLiterals name="remote"/>
      <eLiterals name="local"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SIPHeader">
      <eLiterals name="CALL_ID"/>
      <eLiterals name="CONTACT"/>
      <eLiterals name="CSEQ"/>
      <eLiterals name="EVENT"/>
      <eLiterals name="FROM"/>
      <eLiterals name="MAX_FORWARDS"/>
      <eLiterals name="SUBSCRIPTION_STATE"/>
      <eLiterals name="TO"/>
      <eLiterals name="VIA"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SuccessKind">
      <eLiterals name="OK"/>
      <eLiterals name="ACCEPTED"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ClientErrorKind">
      <eLiterals name="ADDRESS_INCOMPLETE"/>
      <eLiterals name="AMBIGUOUS"/>
      <eLiterals name="BAD_EXTENSION"/>
      <eLiterals name="BAD_REQUEST"/>
      <eLiterals name="BUSY_HERE"/>
      <eLiterals name="CALL_OR_TRANSACTION_DOES_NOT_EXIST"/>
      <eLiterals name="EXTENSION_REQUIRED"/>
      <eLiterals name="FORBIDDEN"/>
      <eLiterals name="GONE"/>
      <eLiterals name="INTERVAL_TOO_BRIEF"/>
      <eLiterals name="LOOP_DETECTED"/>
      <eLiterals name="METHOD_NOT_ALLOWED"/>
      <eLiterals name="NOT_ACCEPTABLE_HERE"/>
      <eLiterals name="NOT_ACCEPTABLE"/>
      <eLiterals name="NOT_FOUND"/>
      <eLiterals name="PAYMENT_REQUIRED"/>
      <eLiterals name="PROXY_AUTHENTICATION_REQUIRED"/>
      <eLiterals name="REQUESTURI_TOO_LONG"/>
      <eLiterals name="REQUEST_ENTITY_TOO_LARGE"/>
      <eLiterals name="REQUEST_PENDING"/>
      <eLiterals name="REQUEST_TERMINATED"/>
      <eLiterals name="REQUEST_TIMEOUT"/>
      <eLiterals name="TEMPORARILY_UNAVAILABLE"/>
      <eLiterals name="TOO_MANY_HOPS"/>
      <eLiterals name="UNAUTHORIZED"/>
      <eLiterals name="UNDECIPHERABLE"/>
      <eLiterals name="UNSUPPORTED_MEDIA_TYPE"/>
      <eLiterals name="UNSUPPORTED_URI_SCHEME"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GlobalErrorKind">
      <eLiterals name="BUSY_EVERYWHERE"/>
      <eLiterals name="DECLINE"/>
      <eLiterals name="DOES_NOT_EXIST_ANYWHERE"/>
      <eLiterals name="NOT_ACCEPTABLE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RedirectionErrorKind">
      <eLiterals name="ALTERNATIVE_SERVICE"/>
      <eLiterals name="MOVED_PERMANENTLY"/>
      <eLiterals name="MOVED_TEMPORARILY"/>
      <eLiterals name="MULTIPLE_CHOICES"/>
      <eLiterals name="USE_PROXY"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ServerErrorKind">
      <eLiterals name="BAD_GATEWAY"/>
      <eLiterals name="MESSAGE_TOO_LARGE"/>
      <eLiterals name="NOT_IMPLEMENTED"/>
      <eLiterals name="SERVER_INTERNAL_ERROR"/>
      <eLiterals name="SERVER_TIMEOUT"/>
      <eLiterals name="SERVICE_UNAVAILABLE"/>
      <eLiterals name="VERSION_NOT_SUPPORTED"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="SPL">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsBefore" unique="false" upperBound="-1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentsAfter" unique="false" upperBound="-1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Program" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" ordered="false" lowerBound="1" eType="/1/Service" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1" eType="/1/Declaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1" eType="/1/Session" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Session" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Registration" eSuperTypes="/1/Session">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1" eType="/1/Declaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1" eType="/1/Session" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dialog" eSuperTypes="/1/Session">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1" eType="/1/Declaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="1" upperBound="-1" eType="/1/Method" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="/1/Session">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventId" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1" eType="/1/Declaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="1" upperBound="-1" eType="/1/Method" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="/1/Session">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/TypeExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false" unique="false" lowerBound="1" eType="/0/Direction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodName" ordered="false" lowerBound="1" eType="/1/MethodName" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/1/Argument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1" upperBound="-1" eType="/1/Branch" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Argument" eSuperTypes="/1/VariableDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="MethodName" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SIPMethodName" eSuperTypes="/1/MethodName">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/SIPMethod"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlMethodName" eSuperTypes="/1/MethodName">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/ControlMethod"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefaultBranch" eSuperTypes="/1/Branch"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedBranch" eSuperTypes="/1/Branch">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1" upperBound="-1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeExpression" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="/1/TypeExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/PrimitiveType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="/1/TypeExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifier" ordered="false" unique="false" eType="/0/Modifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false" lowerBound="1" eType="/0/PrimitiveType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false" eType="/2/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefinedType" eSuperTypes="/1/TypeExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="/1/Declaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/TypeExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExp" ordered="false" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" abstract="true" eSuperTypes="/1/Declaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" ordered="false" lowerBound="1" eType="/1/TypeExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="/1/Argument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RemoteFunctionDeclaration" eSuperTypes="/1/FunctionDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionLocation" ordered="false" unique="false" lowerBound="1" eType="/0/FunctionLocation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalFunctionDeclaration" eSuperTypes="/1/FunctionDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureDeclaration" eSuperTypes="/1/Declaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1" upperBound="-1" eType="/1/Argument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureProperty" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1" eType="/1/TypeExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" ordered="false" lowerBound="1" eType="/1/FunctionDeclaration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" lowerBound="1" eType="/1/Place" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="setValue" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclarationStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" ordered="false" lowerBound="1" eType="/1/Declaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnedValue" ordered="false" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="branch" ordered="false" eType="/1/NamedBranch"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenStatements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatements" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhenStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="idExp" ordered="false" lowerBound="1" eType="/1/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="whenHeaders" lowerBound="1" upperBound="-1" eType="/1/WhenHeader" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatements" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForeachStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteratorName" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceExp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="matchedExp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectCases" upperBound="-1" eType="/1/SelectCase" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectDefault" ordered="false" eType="/1/SelectDefault" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionCallStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="functionCall" ordered="false" lowerBound="1" eType="/1/FunctionCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContinueStat" eSuperTypes="/1/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="BreakStat" eSuperTypes="/1/Statement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PushStat" eSuperTypes="/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false" lowerBound="1" eType="/1/Place" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pushedValue" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhenHeader" eSuperTypes="/1/VariableDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerId" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="/1/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectMember" abstract="true" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SelectDefault" eSuperTypes="/1/SelectMember"/>
    <eClassifiers xsi:type="ecore:EClass" name="SelectCase" eSuperTypes="/1/SelectMember">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1" upperBound="-1" eType="/1/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstantExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" lowerBound="1" eType="/1/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperatorExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opName" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExp" ordered="false" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForwardExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isParallel" ordered="false" unique="false" lowerBound="1" eType="/2/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" ordered="false" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WithExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="msgFields" lowerBound="1" upperBound="-1" eType="/1/MessageField" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReasonExp" eSuperTypes="/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="BODYExp" eSuperTypes="/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequestURIExp" eSuperTypes="/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="PopExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" lowerBound="1" eType="/1/Place" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionCallExp" eSuperTypes="/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="functionCall" ordered="false" lowerBound="1" eType="/1/FunctionCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Place" abstract="true" eSuperTypes="/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="SIPHeaderPlace" eSuperTypes="/1/Place">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" ordered="false" unique="false" lowerBound="1" eType="/0/SIPHeader"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariablePlace" abstract="true" eSuperTypes="/1/Place"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyCallPlace" eSuperTypes="/1/VariablePlace">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propName" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" lowerBound="1" eType="/1/VariablePlace" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="/1/VariablePlace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false" lowerBound="1" eType="/1/Declaration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageField" abstract="true" eSuperTypes="/1/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" ordered="false" lowerBound="1" eType="/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReasonMessageField" eSuperTypes="/1/MessageField"/>
    <eClassifiers xsi:type="ecore:EClass" name="HeadedMessageField" eSuperTypes="/1/MessageField">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerId" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/2/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/2/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="URIConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" unique="false" lowerBound="1" eType="/2/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1" eType="/1/Constant" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponseConstant" eSuperTypes="/1/Constant">
      <eStructuralFeatures xsi:type="ecore:EReference" name="response" ordered="false" lowerBound="1" eType="/1/Response" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Response" abstract="true" eSuperTypes="/1/LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SuccessResponse" eSuperTypes="/1/Response">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="successKind" ordered="false" unique="false" lowerBound="1" eType="/0/SuccessKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ErrorResponse" eSuperTypes="/1/Response"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClientErrorResponse" eSuperTypes="/1/ErrorResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorKind" ordered="false" unique="false" eType="/0/ClientErrorKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GlobalErrorResponse" eSuperTypes="/1/ErrorResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorKind" ordered="false" unique="false" eType="/0/GlobalErrorKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RedirectionErrorResponse" eSuperTypes="/1/ErrorResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorKind" ordered="false" unique="false" eType="/0/RedirectionErrorKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerErrorResponse" eSuperTypes="/1/ErrorResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorKind" ordered="false" unique="false" eType="/0/ServerErrorKind"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
  </ecore:EPackage>
</xmi:XMI>
