<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
  </ecore:EPackage>
  <ecore:EPackage name="BibTeX">
    <eClassifiers xsi:type="ecore:EClass" name="BibTeXFile">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" ordered="false" upperBound="-1" eType="/1/BibTeXEntry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Author">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BibTeXEntry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AuthoredEntry" abstract="true" eSuperTypes="/1/BibTeXEntry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="authors" ordered="false" lowerBound="1" upperBound="-1" eType="/1/Author" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DatedEntry" abstract="true" eSuperTypes="/1/BibTeXEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TitledEntry" abstract="true" eSuperTypes="/1/BibTeXEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BookTitledEntry" abstract="true" eSuperTypes="/1/BibTeXEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="booktitle" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="/1/AuthoredEntry /1/DatedEntry /1/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="journal" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TechReport" eSuperTypes="/1/AuthoredEntry /1/DatedEntry /1/TitledEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Unpublished" eSuperTypes="/1/AuthoredEntry /1/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Manual" eSuperTypes="/1/TitledEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Proceedings" eSuperTypes="/1/DatedEntry /1/TitledEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="InProceedings" eSuperTypes="/1/Proceedings /1/AuthoredEntry /1/BookTitledEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Booklet" eSuperTypes="/1/DatedEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="/1/AuthoredEntry /1/DatedEntry /1/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InCollection" eSuperTypes="/1/Book /1/BookTitledEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="InBook" eSuperTypes="/1/Book">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" ordered="false" lowerBound="1" eType="/0/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Misc" eSuperTypes="/1/BibTeXEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThesisEntry" abstract="true" eSuperTypes="/1/AuthoredEntry /1/DatedEntry /1/TitledEntry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="school" ordered="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhDThesis" eSuperTypes="/1/ThesisEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="MasterThesis" eSuperTypes="/1/ThesisEntry"/>
  </ecore:EPackage>
</xmi:XMI>
