<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dbmodel"
    nsURI="http://www.postfinance.ch/zvis/zimt/dbmodel/Dbmodel" nsPrefix="dbmodel">
  <eClassifiers xsi:type="ecore:EClass" name="DbModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mtype" eType="#//Mtype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kudaType" eType="#//KudaType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kobeType" eType="#//KobeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" upperBound="-1"
        eType="#//Subject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duplicates" upperBound="-1"
        eType="#//Duplicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//ClassOrDuplicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//Subject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDBio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publish" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vmaj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pubspec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pubname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="whereclause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archivIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primkey" eType="#//Primkey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" upperBound="-1"
        eType="#//Index" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdbs" upperBound="-1" eType="#//Pdb"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Duplicate" eSuperTypes="#//ClassOrDuplicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orig" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Ltype"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreign" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forattr" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exttable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extattr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kuko" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kukoindex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kukoonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shrs" upperBound="-1" eType="#//StructShare"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ovride" upperBound="-1"
        eType="#//StructOverride" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archiv" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sybident" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logattr" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInDB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primkey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pkeys" unique="false" upperBound="-1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kuko" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" unique="false" upperBound="-1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimkey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clustered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attr" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pdb">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//PhysicalDatabase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" upperBound="-1"
        eType="#//IndexRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockSchema" eType="#//LockSchema"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tablePartitioning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ltype">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../../ch.postfinance.zvis.primitives/src-gen/ch/postfinance/zvis/primitives/Primitives.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructOverride">
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="ecore:EClass ../../../../../../../ch.postfinance.zvis.primitives/src-gen/ch/postfinance/zvis/primitives/Primitives.ecore#//Stype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructShare">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attr" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="ecore:EClass ../../../../../../../ch.postfinance.zvis.primitives/src-gen/ch/postfinance/zvis/primitives/Primitives.ecore#//Stype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mtype">
    <eLiterals name="KUDA" literal="Kuda"/>
    <eLiterals name="KOBE" value="1" literal="Kobe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KudaType">
    <eLiterals name="MAIN" literal="Kuda-Main"/>
    <eLiterals name="PUBLISH" value="1" literal="Kuda-Publish"/>
    <eLiterals name="TIPO" value="2" literal="Kuda-Tipo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KobeType">
    <eLiterals name="MAIN" literal="Kobe-Main"/>
    <eLiterals name="AUSW" value="1" literal="Kobe-Auswertung"/>
    <eLiterals name="KORA" value="2" literal="Kobe-Kora"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KudaReplicate">
    <eLiterals name="PUBLISH" literal="Krep-Publish"/>
    <eLiterals name="PUBLISHSTV" value="1" literal="Krep-Publish-Stv"/>
    <eLiterals name="DWH" value="2" literal="Krep-DWH"/>
    <eLiterals name="SNAP" value="3" literal="Krep-Snap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalDatabase">
    <eLiterals name="PDB_ABFRAGE_ARCHIV" literal="PDB_ABFRAGE_ARCHIV"/>
    <eLiterals name="PDB_ABFRAGE_BUCH_STAMM" value="1" literal="PDB_ABFRAGE_BUCH_STAMM"/>
    <eLiterals name="PDB_ABFRAGE_ETV" value="2" literal="PDB_ABFRAGE_ETV"/>
    <eLiterals name="PDB_ABFRAGE_FZK" value="3" literal="PDB_ABFRAGE_FZK"/>
    <eLiterals name="PDB_ABFRAGE_MON" value="4" literal="PDB_ABFRAGE_MON"/>
    <eLiterals name="PDB_ABFRAGE_PKT_STAMM" value="5" literal="PDB_ABFRAGE_PKT_STAMM"/>
    <eLiterals name="PDB_ABFRAGE_VSTI" value="6" literal="PDB_ABFRAGE_VSTI"/>
    <eLiterals name="PDB_AUSW_KOBE_ARCHIV" value="7" literal="PDB_AUSW_KOBE_ARCHIV"/>
    <eLiterals name="PDB_AUSW_KOBE_BUCH_STAMM" value="8" literal="PDB_AUSW_KOBE_BUCH_STAMM"/>
    <eLiterals name="PDB_AUSW_KOBE_MON" value="9" literal="PDB_AUSW_KOBE_MON"/>
    <eLiterals name="PDB_AUSW_KOBE_PKT_STAMM" value="10" literal="PDB_AUSW_KOBE_PKT_STAMM"/>
    <eLiterals name="PDB_AUSW_KOBE_STATISTIK" value="11" literal="PDB_AUSW_KOBE_STATISTIK"/>
    <eLiterals name="PDB_KOBE_AUSW_ADMIN" value="12" literal="PDB_KOBE_AUSW_ADMIN"/>
    <eLiterals name="PDB_KOBE_DATA" value="13" literal="PDB_KOBE_DATA"/>
    <eLiterals name="PDB_KOBE_DEZ_STAMM" value="14" literal="PDB_KOBE_DEZ_STAMM"/>
    <eLiterals name="PDB_KOBE_KNDTEST" value="15" literal="PDB_KOBE_KNDTEST"/>
    <eLiterals name="PDB_KOBE_PMON" value="16" literal="PDB_KOBE_PMON"/>
    <eLiterals name="PDB_KOBE_STAMM" value="17" literal="PDB_KOBE_STAMM"/>
    <eLiterals name="PDB_KOBE_STEUERUNG" value="18" literal="PDB_KOBE_STEUERUNG"/>
    <eLiterals name="PDB_KOBE_GLOBAL" value="19" literal="PDB_KOBE_GLOBAL"/>
    <eLiterals name="PDB_KUDA_TRANS_TRANSIT" value="20" literal="PDB_KUDA_TRANS_TRANSIT"/>
    <eLiterals name="PDB_MANDANT_BUCH_PROV" value="21" literal="PDB_MANDANT_BUCH_PROV"/>
    <eLiterals name="PDB_MANDANT_BUCH_STAMM" value="22" literal="PDB_MANDANT_BUCH_STAMM"/>
    <eLiterals name="PDB_MANDANT_MON" value="23" literal="PDB_MANDANT_MON"/>
    <eLiterals name="PDB_MANDANT_PKT_DATA" value="24" literal="PDB_MANDANT_PKT_DATA"/>
    <eLiterals name="PDB_MANDANT_PKT_STAMM" value="25" literal="PDB_MANDANT_PKT_STAMM"/>
    <eLiterals name="PDB_MANDANT_TAG" value="26" literal="PDB_MANDANT_TAG"/>
    <eLiterals name="PDB_MANDANT_TAG_A" value="27" literal="PDB_MANDANT_TAG_A"/>
    <eLiterals name="PDB_PART_AUFT" value="28" literal="PDB_PART_AUFT"/>
    <eLiterals name="PDB_PART_BUCH_PROV" value="29" literal="PDB_PART_BUCH_PROV"/>
    <eLiterals name="PDB_PART_BUCH_STAMM" value="30" literal="PDB_PART_BUCH_STAMM"/>
    <eLiterals name="PDB_PART_JAHR" value="31" literal="PDB_PART_JAHR"/>
    <eLiterals name="PDB_PART_MON" value="32" literal="PDB_PART_MON"/>
    <eLiterals name="PDB_PART_PKT_DATA" value="33" literal="PDB_PART_PKT_DATA"/>
    <eLiterals name="PDB_PART_PKT_STAMM" value="34" literal="PDB_PART_PKT_STAMM"/>
    <eLiterals name="PDB_PART_TAG" value="35" literal="PDB_PART_TAG"/>
    <eLiterals name="PDB_PART_TAG_A" value="36" literal="PDB_PART_TAG_A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LockSchema">
    <eLiterals name="ALLPAGES" literal="ALLPAGES"/>
    <eLiterals name="DATAPAGES" value="1" literal="DATAPAGES"/>
    <eLiterals name="DATAROWS" value="2" literal="DATAROWS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassOrDuplicate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abbrev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reps" unique="false" upperBound="-1"
        eType="#//KudaReplicate"/>
  </eClassifiers>
</ecore:EPackage>
