<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pETRI"
    nsURI="http://www.enseeiht.fr/PETRI" nsPrefix="pETRI">
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="petriNetElements" upperBound="-1"
        eType="ecore:EClass platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//PetriNetElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//PetriNetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//PetriNetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="ecore:EClass platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="ecore:EClass platform:/resource/fr.enseeiht.petrinet.t2m/src-gen/fr/enseeiht/PETRI.ecore#//Node"/>
  </eClassifiers>
</ecore:EPackage>
