<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Comp_Feaut"
    nsURI="http://Comp_Feaut" nsPrefix="Comp_Feaut">
  <eSubpackages name="feature" nsURI="feature" nsPrefix="feature">
    <eClassifiers xsi:type="ecore:EClass" name="Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="PortGroup"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="Subprogram"/>
    <eClassifiers xsi:type="ecore:EClass" name="Features">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
          eType="#//feature/Features" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubprogramFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="SoftwareFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadGroupFeatures" eSuperTypes="#//feature/Features"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventDataPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataAccess"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="SystemFeatures" eSuperTypes="#//feature/Features"/>
  </eSubpackages>
  <eSubpackages name="component" nsURI="component" nsPrefix="component">
    <eClassifiers xsi:type="ecore:EClass" name="SubprogramImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/SubprogramImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/SubprogramSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/ProcessImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/ProcessSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/SystemImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/SystemSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/DataImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/DataSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/ThreadImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/ThreadSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/DeviceImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/DeviceSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadGroupImpl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//component/ThreadGroupImpl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subcomponents" eType="#//component/ThreadGroupSubcomponents"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" eType="#//connection/Connections"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/SystemSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/DataSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/ThreadSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadGroupSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/ThreadGroupSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/ProcessSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubprogramSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/SubprogramSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceSubcomponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//component/DeviceSubcomponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/SystemFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/DeviceFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/DataFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/ThreadFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/ProcessFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubprogramType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/SubprogramFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadGroupType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//feature/ThreadGroupFeatures"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubprogramSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="SystemSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeviceSubcomponents"/>
    <eClassifiers xsi:type="ecore:EClass" name="ThreadGroupSubcomponents"/>
  </eSubpackages>
  <eSubpackages name="connection" nsURI="connection" nsPrefix="connection">
    <eClassifiers xsi:type="ecore:EClass" name="DataConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataAccessConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="EventDataConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="Connections">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
          eType="#//connection/Connections" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
