<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prototip"
 nsURI="prototip_prototip.xmi" nsPrefix="prototip">
  <eClassifiers xsi:type="ecore:EEnum" name="TezinaPosla">
     <eLiterals name="LAGAN" literal="LAGAN">
     </eLiterals>
     <eLiterals name="SREDNJI" literal="SREDNJI">
     </eLiterals>
     <eLiterals name="TEZAK" literal="TEZAK">
     </eLiterals>
     <eLiterals name="VRLO_TEZAK" literal="VRLO_TEZAK">
     </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Angazovani_Radnik" abstract="true">
     <eReferences name="radina" eType="#//Posao" transient="true" unique="true"  lowerBound="0" upperBound="-1" ordered ="false">
     </eReferences>
     <eAttributes name="ime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="false" unique="true">
     </eAttributes>
     <eAttributes name="prezime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="false" unique="true">
     </eAttributes>
     <eAttributes name="plata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" transient="false" unique="true">
     </eAttributes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visokokvalifikovani_Radnik" eSuperTypes="#//Angazovani_Radnik" abstract="true">
     <eAttributes name="naziv skole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="false" unique="true">
     </eAttributes>
     <eAttributes name="stepen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" transient="false" unique="true">
     </eAttributes>
     <eAttributes name="drzavni?" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="false" unique="true">
     </eAttributes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visa_Skola" eSuperTypes="#//Visokokvalifikovani_Radnik">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fakultetski_Obrazovan" eSuperTypes="#//Visokokvalifikovani_Radnik">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fizikalac" eSuperTypes="#//Angazovani_Radnik">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Posao">
     <eReferences name="podposao" eType="#//Posao" transient="true" unique="true"  lowerBound="0" upperBound="-1" ordered ="false">
     </eReferences>
     <eAttributes name="naziv" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="false" unique="true">
     </eAttributes>
     <eAttributes name="tezina" eType="#//TezinaPosla" transient="false" unique="true">
     </eAttributes>
  </eClassifiers>
</ecore:EPackage>