<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="account" nsURI="http://www.eclipselabs.org/etrack/domain/account"
    nsPrefix="org.eclipselabs.etrack.domain.account">
  <eClassifiers xsi:type="ecore:EClass" name="Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Entity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountRequest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.security/model/security.ecore#//PasswordCredential"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.entity/model/entity.ecore#//Entity"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" lowerBound="1"
        eType="ecore:EClass ../../org.eclipselabs.etrack.domain.security/model/security.ecore#//PasswordCredential"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
