<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="build"
    nsURI="http://www.eclipse.org/emf/mwe/ewm/workflow/examples/build" nsPrefix="org.eclipse.emf.mwe.ewm.workflow.examples.build">
  <eClassifiers xsi:type="ecore:EClass" name="JavaCompiler" eSuperTypes="../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowUnitOfWork">
    <eOperations name="run" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/state/WorkflowState">
      <eParameters name="context" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/WorkflowContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classNameParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classpathParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workingDirectoryParameter"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaJar" eSuperTypes="../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowUnitOfWork">
    <eOperations name="run" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/state/WorkflowState">
      <eParameters name="context" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/WorkflowContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classNameParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workingDirectoryParameter"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputFileParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZipFile" eSuperTypes="../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowUnitOfWork">
    <eOperations name="run" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/state/WorkflowState">
      <eParameters name="context" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//runtime/WorkflowContext"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workingDirectoryParameter"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFileParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputFileParameter" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.mwe.ewm.core/model/workflow.ecore#//WorkflowParameter"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
