<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="car"
    nsURI="http://www.kermeta.org/car" nsPrefix="car">
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EReference" name="motor" lowerBound="1" upperBound="-1"
        eType="#//Motor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Motor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Petrol" eSuperTypes="#//Motor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Diesel" eSuperTypes="#//Motor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Option" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GPS" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="AirCond" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Radio" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aircond" eSuperTypes="#//Option"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABS" eSuperTypes="#//Option"/>
</ecore:EPackage>
