<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="claim"
    nsURI="http://www.eclipse.org/emf/teneo/samples/emf/sample/claim" nsPrefix="claim">
  <eClassifiers xsi:type="ecore:EClass" name="Claim">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Claim Information"/>
    </eAnnotations>
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="&#x9;&#xA;&#x9;@Table(&#xA;&#x9;  name=PCLM_NPRC_CLM&#xA;&#x9;  uniqueConstraints = {&#x9;@UniqueConstraint(columnNames={&quot;CLM_NBR&quot;, &quot;CLM_EXT_NBR&quot;})&#xA;&#x9;  &#x9;&#x9;&#x9;&#x9;&#x9;  }&#x9;  &#xA;&#x9;)&#xA;&#x9;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Claim"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claimCompositeKey" lowerBound="1"
        eType="#//ClaimCompositeKey" containment="true" resolveProxies="false">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@EmbeddedId"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimCompositeKey"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="billingName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Billing Name"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Column(name=BILLING_NAME,length=&quot;50&quot;)"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="billingName"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimGroupVSPId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Claim Group VSP Id"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Column(name=CLM_GRP_VSP_ID,length=&quot;3&quot;)"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimGroupVSPId"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimStatus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""
        unsettable="true">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Column(name=CLM_STATUS,length=&quot;2&quot;)"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimStatus"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claimLine" upperBound="-1"
        eType="#//ClaimLine" containment="true" resolveProxies="false" eOpposite="#//ClaimLine/claim">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@OneToMany(mappedBy=&quot;ClaimLine&quot;, indexed=false)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@JoinColumns({&#xA;    &#x9;&#x9;&#x9;&#x9;&#x9;@JoinColumn(name=&quot;CLM_NBR&quot;),&#xA;    &#x9;&#x9;&#x9;&#x9;&#x9;@JoinColumn(name=&quot;CLM_EXT_NBR&quot;)&#xA;    &#x9;&#x9;&#x9;&#x9;})&#x9;&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimLine"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimCompositeKey">
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@Embeddable"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ClaimCompositeKey"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;The Unique Identifier for a Claim. &#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@Column(name=CLM_NBR)&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimNumber"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimExtensionNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;The Unique Identifier for a Claim. &#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@Column(name=CLM_EXT_NBR)&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimExtensionNumber"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimLine">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Claim Line Information"/>
    </eAnnotations>
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="&#x9;&#xA;&#x9;&#x9;@Table(&#xA;&#x9;&#x9;  name=PCLM_NPRC_CLMLN&#x9;&#x9;  &#xA;&#x9;&#x9;  uniqueConstraints = {&#x9;@UniqueConstraint(columnNames={&quot;CLM_NBR&quot;, &quot;CLM_EXT_NBR&quot;, &quot;CLMLN_NBR&quot;})&#xA;&#x9;&#x9;  &#x9;&#x9;&#x9;&#x9;&#x9;  }&#x9;  &#xA;&#x9;&#x9; )&#xA;&#x9;&#x9;"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ClaimLine"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claim" lowerBound="1" eType="#//Claim"
        resolveProxies="false" eOpposite="#//Claim/claimLine">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A generated key to uniquely the parent"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;@Transient&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claim"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claimLineCompositeKey"
        lowerBound="1" eType="#//ClaimLineCompositeKey" containment="true" resolveProxies="false">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@EmbeddedId"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimLineCompositeKey"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimLineBilledAmount"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Decimal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;The Unique Identifier for a Claim. &#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@Column(name=CLMLN_BILL_AMT)&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimLineBilledAmount"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;The Unique Identifier for a Claim. &#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@Column(name=SVC_CD)&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="serviceCode"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimLineStatus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral=""
        unsettable="true">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Column(name=CLMLN_STATUS,length=&quot;2&quot;)"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimLineStatus"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaimLineCompositeKey">
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@Embeddable"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ClaimLineCompositeKey"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claim" lowerBound="1" eType="#//Claim"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A generated key to uniquely the parent"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;@ManyToOne&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;@JoinColumns({&#xA;&#x9;&#x9;    &#x9;&#x9;&#x9;&#x9;@JoinColumn(name=&quot;CLM_NBR&quot;, referencedColumnName = &quot;CLM_NBR&quot;),&#xA;&#x9;&#x9;    &#x9;&#x9;&#x9;&#x9;@JoinColumn(name=&quot;CLM_EXT_NBR&quot;, referencedColumnName =&quot;CLM_EXT_NBR&quot;)&#xA;&#x9;&#x9;    &#x9;&#x9;&#x9;})&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claim"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="claimLineNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;The Unique Identifier for a Claim. &#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;@Column(name=CLMLN_NBR)&#xA;&#x9;&#x9;&#x9;&#x9;"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="claimLineNumber"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
