<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="closures"
    nsURI="http://www.emftext.org/language/java/closures" nsPrefix="closures">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClosureCall" abstract="true"
      eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//statements/Statement ../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression ../../org.emftext.language.java/metamodel/java.ecore#//references/Argumentable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractClosure" abstract="true" eSuperTypes="../../org.emftext.language.java/metamodel/java.ecore#//members/Member ../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parameter ../../org.emftext.language.java/metamodel/java.ecore#//expressions/Expression ../../org.emftext.language.java/metamodel/java.ecore#//statements/StatementListContainer ../../org.emftext.language.java/metamodel/java.ecore#//parameters/Parametrizable ../../org.emftext.language.java/metamodel/java.ecore#//references/Reference ../../org.emftext.language.java/metamodel/java.ecore#//expressions/PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterTypes" upperBound="-1"
        eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" lowerBound="1"
        eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//types/TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueTypeArrayDimension"
        upperBound="-1" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//arrays/ArrayDimension"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Closure" eSuperTypes="#//AbstractClosure"/>
</ecore:EPackage>
