<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cp1model" nsURI="http://inf.mit.bme.hu/donat/incquery-deps/cp1model"
    nsPrefix="cp1">
  <eClassifiers xsi:type="ecore:EClass" name="CP1Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//CP1Project" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//CP1Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1Project" eSuperTypes="#//CP1CodeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//CP1Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//CP1CodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//CP1CodeElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CP1DependencyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1Class" eSuperTypes="#//CP1CodeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//CP1Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//CP1Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1Method" eSuperTypes="#//CP1CodeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1Field" eSuperTypes="#//CP1CodeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP1CodeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CP1DependencyType">
    <eLiterals name="METHOD_CALL" value="1" literal="1"/>
    <eLiterals name="METHOD_OVERRIDE" value="2" literal="2"/>
    <eLiterals name="FIELD_REFERENCE" value="3" literal="3"/>
    <eLiterals name="CLASS_USAGE" value="4" literal="4"/>
    <eLiterals name="INHERITANCE" value="5" literal="5"/>
  </eClassifiers>
</ecore:EPackage>
