<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dbdefinition"
    nsURI="http:///org/eclipse/datatools/modelbase/dbdefinition/dbdefinition.ecore"
    nsPrefix="DBDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseVendorDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedDataTypeDefinitions"
        upperBound="-1" eType="#//PredefinedDataTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableSpaceDefinition" lowerBound="1"
        eType="#//TableSpaceDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedProcedureDefinition"
        lowerBound="1" eType="#//StoredProcedureDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggerDefinition" lowerBound="1"
        eType="#//TriggerDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnDefinition" lowerBound="1"
        eType="#//ColumnDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintDefinition" lowerBound="1"
        eType="#//ConstraintDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedDefinitions" upperBound="-1"
        eType="#//ExtendedDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexDefinition" lowerBound="1"
        eType="#//IndexDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableDefinition" lowerBound="1"
        eType="#//TableDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceDefinition" lowerBound="1"
        eType="#//SequenceDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="udtDefinition" lowerBound="1"
        eType="#//UserDefinedTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryDefinition" lowerBound="1"
        eType="#//QueryDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SQLSyntaxDefinition" lowerBound="1"
        eType="#//SQLSyntaxDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nicknameDefinition" lowerBound="1"
        eType="#//NicknameDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemaDefinition" lowerBound="1"
        eType="#//SchemaDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewDefinition" lowerBound="1"
        eType="#//ViewDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="debuggerDefinition" lowerBound="1"
        eType="#//DebuggerDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privilegedElementDefinitions"
        upperBound="-1" eType="#//PrivilegedElementDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructedDataTypeDefinition"
        lowerBound="1" eType="#//ConstructedDataTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintsSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="snapshotViewSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="joinSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewTriggerSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tablespacesSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCommentLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mQTSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aliasSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synonymSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDefinedTypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SQLStatementSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nicknameSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotedDMLSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quotedDDLSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmlSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mQTIndexSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqlUDFSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storedProcedureSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizationIdentifierSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleAuthorizationSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructedDataTypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uDFSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedDataTypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadingFieldQualifierDefinition"
        upperBound="-1" eType="#//FieldQualifierDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trailingFieldQualifierDefinition"
        upperBound="-1" eType="#//FieldQualifierDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultTrailingFieldQualifierDefinition"
        eType="#//FieldQualifierDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultLeadingFieldQualifierDefinition"
        eType="#//FieldQualifierDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaleSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precisionSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identitySupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleColumnsSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullableSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusteringSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillFactorSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitDataSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" eType="ecore:EEnum ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//datatypes/PrimitiveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jdbcEnumType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterSet" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingScheme" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterSetSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingSchemeSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cutoffPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthUnit" eType="#//LengthUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderingSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupingSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayNameSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leadingFieldQualifierSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trailingFieldQualifierSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldQualifierSeparator"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeValueSpecifierSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeValueSpecifierName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeValueSpecifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthSemanticSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthSemantic" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageType" upperBound="-1"
        eType="#//LanguageType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CheckOption">
    <eLiterals name="NONE"/>
    <eLiterals name="CASCADE" value="1"/>
    <eLiterals name="LOCAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageType">
    <eLiterals name="SQL"/>
    <eLiterals name="JAVA" value="1"/>
    <eLiterals name="C" value="2"/>
    <eLiterals name="OLE" value="3"/>
    <eLiterals name="ASSEMBLY" value="4"/>
    <eLiterals name="COBOL" value="5"/>
    <eLiterals name="PLI" value="6"/>
    <eLiterals name="CPLUSPLUS" value="7"/>
    <eLiterals name="CL" value="8"/>
    <eLiterals name="COBOLLE" value="9"/>
    <eLiterals name="FORTRAN" value="10"/>
    <eLiterals name="REXX" value="11"/>
    <eLiterals name="RPG" value="12"/>
    <eLiterals name="RPGLE" value="13"/>
    <eLiterals name="PLSQL" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterStyle">
    <eLiterals name="DB2SQL"/>
    <eLiterals name="GENERAL" value="1"/>
    <eLiterals name="GENERAL_WITH_NULLS" value="2"/>
    <eLiterals name="DB2GENRL" value="3"/>
    <eLiterals name="DB2DARI" value="4"/>
    <eLiterals name="JAVA" value="5"/>
    <eLiterals name="SQL" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParentDeleteDRIRuleType">
    <eLiterals name="NO_ACTION"/>
    <eLiterals name="RESTRICT" value="1"/>
    <eLiterals name="CASCADE" value="2"/>
    <eLiterals name="SET_NULL" value="3"/>
    <eLiterals name="SET_DEFAULT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParentUpdateDRIRuleType">
    <eLiterals name="NO_ACTION"/>
    <eLiterals name="RESTRICT" value="1"/>
    <eLiterals name="CASCADE" value="2"/>
    <eLiterals name="SET_NULL" value="3"/>
    <eLiterals name="SET_DEFAULT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcedureType">
    <eLiterals name="PROCEDURE"/>
    <eLiterals name="FUNCTION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TableSpaceType">
    <eLiterals name="REGULAR"/>
    <eLiterals name="LOB" value="1"/>
    <eLiterals name="SYSTEM_TEMPORARY" value="2"/>
    <eLiterals name="USER_TEMPORARY" value="3"/>
    <eLiterals name="PERMANENT" value="4"/>
    <eLiterals name="TEMPORARY" value="5"/>
    <eLiterals name="LONG" value="6"/>
    <eLiterals name="LARGE" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableSpaceDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extentSizeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefetchSizeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managedBySupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSizeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferPoolSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerMaximumSizeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerInitialSizeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerExtentSizeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableSpaceType" upperBound="-1"
        eType="#//TableSpaceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoredProcedureDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedDataTypeDefinitions"
        upperBound="-1" eType="#//PredefinedDataTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullInputActionSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageGenerationSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="determininsticSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnedNullSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnedTypeDeclarationConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterInitValueSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterStyleSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnTypeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterDeclarationConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumActionBodyLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterStyle" upperBound="-1"
        eType="#//ParameterStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageType" upperBound="-1"
        eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionLanguageType" upperBound="-1"
        eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procedureType" upperBound="-1"
        eType="#//ProcedureType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumReferencePartLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumActionBodyLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="whenClauseSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="granularitySupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencesClauseSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perColumnUpdateTriggerSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insteadOfTriggerSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowTriggerReferenceSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableTriggerReferenceSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identityColumnDataTypeDefinitions"
        lowerBound="1" upperBound="-1" eType="#//PredefinedDataTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identitySupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computedSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityStartValueSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityIncrementSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityMinimumSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityMaximumSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identityCycleSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deferrableConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="informationalConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusteredPrimaryKeySupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusteredUniqueConstraintSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKeyNullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueKeyNullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCheckExpressionLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentUpdateDRIRuleType"
        upperBound="-1" eType="#//ParentUpdateDRIRuleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentDeleteDRIRuleType"
        upperBound="-1" eType="#//ParentDeleteDRIRuleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOption" upperBound="-1"
        eType="#//CheckOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPrimaryKeyIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumForeignKeyIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCheckConstraintIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PercentFreeTerminology">
    <eLiterals name="PERCENT_FREE"/>
    <eLiterals name="FILL_FACTOR" value="1"/>
    <eLiterals name="THRESHOLD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentFreeTerminology"
        eType="#//PercentFreeTerminology"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentFreeChangeable"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusteringSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusterChangeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillFactorSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includedColumnsSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auditSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataCaptureSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editProcSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodingSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validProcSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predefinedDataTypeDefinitions"
        lowerBound="1" upperBound="-1" eType="#//PredefinedDataTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultDataTypeDefinition"
        lowerBound="1" eType="#//PredefinedDataTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeEnumerationSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMaximumValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMinimumValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noCacheString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedTypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinctTypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structuredTypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifierQuoteString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="\&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostVariableMarker" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=":"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostVariableMarkerSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="castExpressionSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultKeywordForInsertValueSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedGroupingSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableAliasInDeleteSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLSyntaxDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operators" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminationCharacter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=";"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LengthUnit">
    <eLiterals name="DECIMAL"/>
    <eLiterals name="BIT" value="1"/>
    <eLiterals name="BYTE" value="2"/>
    <eLiterals name="DOUBLE_BYTE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NicknameDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumIdentifierLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOptionSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOptionLevelsSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldQualifierDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validTrailingFieldQualifierDefinitions"
        upperBound="-1" eType="#//FieldQualifierDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EEnum ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//datatypes/IntervalQualifierType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precisionSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaleSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DebuggerDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivilegedElementDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="privilegeDefinitions" upperBound="-1"
        eType="#//PrivilegeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivilegeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionElementDefinitions"
        upperBound="-1" eType="#//PrivilegedElementDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructedDataTypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayDatatypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multisetDatatypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowDatatypeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceDatatypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cursorDatatypeSupported"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
