<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname1" nsURI="http://defaultname1/1.0" nsPrefix="defaultname1">
  <eSubpackages name="Transportation">
    <eClassifiers xsi:type="ecore:EClass" name="Vehicles">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mileage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cars" eSuperTypes="#//Transportation/Vehicles">
      <eOperations name="getModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="has a" eType="#//Transportation/Engine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Transportation/Passengers"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Buses" eSuperTypes="#//Transportation/Vehicles">
      <eStructuralFeatures xsi:type="ecore:EReference" name="has a" eType="#//Transportation/Engine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="#//Transportation/Passengers"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="#//Transportation/Vehicles">
      <eStructuralFeatures xsi:type="ecore:EReference" name="has a" eType="#//Transportation/Engine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Engine">
      <eOperations name="getType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Transportation/Truck"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Passengers"/>
  </eSubpackages>
</ecore:EPackage>
