<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="description" nsURI="http://www.uppaal.org/xml/description/Description"
    nsPrefix="description">
  <eClassifiers xsi:type="ecore:EClass" name="Top"/>
  <eClassifiers xsi:type="ecore:EClass" name="UASystemDefinition" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//UADefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//UASystem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UADefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAInstantiation" eSuperTypes="#//UADefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//UAParameters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//UAExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" upperBound="-1"
        eType="#//UASystemID" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASystemID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAArrayDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UADeclarations" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//UADeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UADeclaration" eSuperTypes="#//UADefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" eType="#//UATypeModifiers"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//UATypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UATypeModifiers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urgent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="broadcast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAVariableDeclaration" eSuperTypes="#//UADeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//UAVariableID" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAVariableID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//UAArrayDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialiser" eType="#//UAInitialiser"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAInitialiser"/>
  <eClassifiers xsi:type="ecore:EClass" name="UASingleInitialiser" eSuperTypes="#//UAInitialiser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMultiInitialiser" eSuperTypes="#//UAInitialiser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialisers" upperBound="-1"
        eType="#//UAInitialiser" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UATypeDeclaration" eSuperTypes="#//UADeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//UATypeID" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UATypeID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//UAArrayDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UATypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAIntegerType" eSuperTypes="#//UATypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAClockType" eSuperTypes="#//UATypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAChannelType" eSuperTypes="#//UATypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UABooleanType" eSuperTypes="#//UATypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAScalarType" eSuperTypes="#//UATypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAStructType" eSuperTypes="#//UATypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//UAFieldDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAFieldDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//UAFieldID" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAFieldID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//UAArrayDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAParameters" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//UAParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//UAArrayDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAExpression" eSuperTypes="#//Top"/>
  <eClassifiers xsi:type="ecore:EClass" name="UASelectList" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selects" upperBound="-1"
        eType="#//UASelect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASelect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAUpdate" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//UAExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASynchronisation" eSuperTypes="#//Top">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UASynchronisationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UASynchronisationType">
    <eLiterals name="EMISSION" literal="!"/>
    <eLiterals name="RECEPTION" value="1" literal="?"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAUserType" eSuperTypes="#//UATypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAForallExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAExistsExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//UAType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAImplyExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UALogicOrExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UALogicAndExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAAdditionAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASubtractionAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMultiplicationAssignmentExpression"
      eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UADivisionAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAModuloAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitOrAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitAndAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitXORAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitLeftAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitRightAssignmentExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAConditionalExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitOrExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitXORExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitAndExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAEqualExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAUnequalExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UALessExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UALessEqualExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAGreaterEqualExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAGreaterExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMinExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMaxExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitLeftExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABitRightExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAAddExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UASubtractExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMultiplyExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UADivideExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAModuloExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAPreIncrementExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAPreDecrementExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UALogicNotExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAMinusExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAPostIncrementExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAPostDecrementExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAStructExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAArrayExpression" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//UAExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//UAExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UAReference" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UABooleanLiteral" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UANumberLiteral" eSuperTypes="#//UAExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
