<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="di"
    nsURI="http://www.soyatec.com/Runtime/DI/1.0" nsPrefix="di">
  <eClassifiers xsi:type="ecore:EClass" name="ContainerShape" abstract="true" eSuperTypes="#//DiNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shapes" upperBound="-1"
        eType="#//Shape" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//ContainerShape">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//DiNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Shape"
        eOpposite="#//Shape/targetLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Shape"
        eOpposite="#//Shape/sourceLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//ContainerShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
