<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eclipsecon"
    nsURI="uri://gmf/examples/eclipsecon" nsPrefix="ec">
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slices" upperBound="5"
        eType="#//TimeSlot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dayNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tutorial">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenters" upperBound="2"
        eType="#//Presenter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigned" eType="#//TimeSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handouts" upperBound="-1"
        eType="#//Handout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutorials" upperBound="20"
        eType="#//Tutorial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendees" upperBound="-1"
        eType="#//Participant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="days" upperBound="2" eType="#//Schedule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipsezilla" upperBound="-1"
        eType="#//Resource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Presenter" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="#//Profile"
        defaultValueLiteral="" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Handout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//HandoutKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipsezilla" eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HandoutKind">
    <eLiterals name="PRINTED"/>
    <eLiterals name="CD"/>
    <eLiterals name="MEM_KEY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Profile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eclipsezilla" eType="#//Resource"/>
  </eClassifiers>
</ecore:EPackage>
