<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edp" nsURI="http://www.wazaabi.org/edp" nsPrefix="edp">
  <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true" interface="true">
    <eOperations name="containsKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return containsKey(key, false);"/>
      </eAnnotations>
      <eParameters name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="containsKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (key == null || &quot;&quot;.equals(key)) //$NON-NLS-1$&#xD;&#xA;&#x9;return false;&#xD;&#xA;for (int i = 0; i &lt; getContents().size(); i++) {&#xD;&#xA;&#x9;ContextContent content = (ContextContent) getContents().get(i);&#xD;&#xA;&#x9;if (key.equals(content.getKey()))&#xD;&#xA;&#x9;&#x9;return true;&#xD;&#xA;}&#xD;&#xA;if (!local&#xD;&#xA;&#x9;&#x9;&amp;&amp; eContainer() instanceof org.eclipse.wazaabi.mm.edp.Context)&#xD;&#xA;&#x9;return ((org.eclipse.wazaabi.mm.edp.Context) eContainer())&#xD;&#xA;&#x9;&#x9;&#x9;.containsKey(key, false);&#xD;&#xA;return false;"/>
      </eAnnotations>
      <eParameters name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="local" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="get" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (key == null || &quot;&quot;.equals(key)) //$NON-NLS-1$&#xD;&#xA;&#x9;return null;&#xD;&#xA;for (int i = 0; i &lt; getContents().size(); i++) {&#xD;&#xA;&#x9;ContextContent content = (ContextContent) getContents().get(i);&#xD;&#xA;&#x9;if (key.equals(content.getKey()))&#xD;&#xA;&#x9;&#x9;return content.getValue();&#xD;&#xA;}&#xD;&#xA;if (eContainer() instanceof org.eclipse.wazaabi.mm.edp.Context)&#xD;&#xA;&#x9;return ((org.eclipse.wazaabi.mm.edp.Context) eContainer())&#xD;&#xA;&#x9;&#x9;&#x9;.get(key);&#xD;&#xA;return null;"/>
      </eAnnotations>
      <eParameters name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="remove">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (key == null || &quot;&quot;.equals(key)) //$NON-NLS-1$&#xD;&#xA;&#x9;return;&#xD;&#xA;&#xD;&#xA;ContextContent content = null;&#xD;&#xA;boolean found = false;&#xD;&#xA;for (int i = 0; i &lt; getContents().size(); i++) {&#xD;&#xA;&#x9;content = (ContextContent) getContents().get(i);&#xD;&#xA;&#x9;if (key.equals(content.getKey())) {&#xD;&#xA;&#x9;&#x9;found = true;&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;if (found)&#xD;&#xA;&#x9;getContents().remove(content);"/>
      </eAnnotations>
      <eParameters name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="set">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (key == null || &quot;&quot;.equals(key)) //$NON-NLS-1$&#xD;&#xA;&#x9;return;&#xD;&#xA;&#xD;&#xA;for (int i = 0; i &lt; getContents().size(); i++) {&#xD;&#xA;&#x9;ContextContent content = (ContextContent) getContents().get(i);&#xD;&#xA;&#x9;if (key.equals(content.getKey())) {&#xD;&#xA;&#x9;&#x9;content.setValue(value);&#xD;&#xA;&#x9;&#x9;return;&#xD;&#xA;&#x9;}&#xD;&#xA;}&#xD;&#xA;ContextContent newContent = org.eclipse.wazaabi.mm.edp.EdpFactory.eINSTANCE&#xD;&#xA;&#x9;&#x9;.createContextContent();&#xD;&#xA;newContent.setKey(key);&#xD;&#xA;newContent.setValue(value);&#xD;&#xA;getContents().add(newContent);"/>
      </eAnnotations>
      <eParameters name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ContextContent" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDispatcher" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//handlers/EventHandler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//handlers/State"/>
  </eClassifiers>
  <eSubpackages name="events" nsURI="http://www.wazaabi.org/edp/events" nsPrefix="edpevts">
    <eClassifiers xsi:type="ecore:EClass" name="PathEvent" abstract="true" eSuperTypes="#//events/Event">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContentChangedEvent" eSuperTypes="#//events/PathEvent"/>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Context">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyChangedEvent" eSuperTypes="#//events/PathEvent"/>
  </eSubpackages>
  <eSubpackages name="handlers" nsURI="http://www.wazaabi.org/edp/handlers" nsPrefix="edphdlrs">
    <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//handlers/Operation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//handlers/EventHandler"/>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//handlers/Deferred #//handlers/Executable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="async" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Executable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//handlers/Executable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="executables" upperBound="-1"
          eType="#//handlers/Executable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deferred">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EventHandler" eSuperTypes="#//handlers/Parameterized #//handlers/Sequence #//handlers/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
          eType="#//events/Event" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
          eType="#//handlers/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameterized" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//handlers/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringParameter" eSuperTypes="#//handlers/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="State"/>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanParameter" eSuperTypes="#//handlers/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntParameter" eSuperTypes="#//handlers/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//handlers/Validator"/>
    <eClassifiers xsi:type="ecore:EClass" name="Validator" eSuperTypes="#//handlers/Operation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Converter" eSuperTypes="#//handlers/Action"/>
  </eSubpackages>
</ecore:EPackage>
