<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esterel" nsURI="http://www.cau.de/cs/kieler/esterel/Esterel"
    nsPrefix="esterel">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="#//ModuleInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ModuleBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSignalDecls" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//InterfaceSignalDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intTypeDecls" upperBound="-1"
        eType="#//TypeDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intSensorDecls" upperBound="-1"
        eType="#//SensorDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intConstantDecls" upperBound="-1"
        eType="#//ConstantDecls" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intRelationDecls" upperBound="-1"
        eType="#//RelationDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intTaskDecls" upperBound="-1"
        eType="#//TaskDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intFunctionDecls" upperBound="-1"
        eType="#//FunctionDecl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intProcedureDecls" upperBound="-1"
        eType="#//ProcedureDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChannelDescription" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ChannelDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeIdentifier" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//TypeIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalDecl" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalList" eType="#//LocalSignalList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignalList"/>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="#//SensorWithType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorWithType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationImplication" eSuperTypes="#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationIncompatibility" eSuperTypes="#//RelationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomp" unique="false"
        upperBound="-1" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDecls">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//OneTypeConstantDecls" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneTypeConstantDecls">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//ConstantWithValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantWithValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList" upperBound="-1"
        eType="#//TypeIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedures" upperBound="-1"
        eType="#//Procedure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList1" upperBound="-1"
        eType="#//TypeIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList2" upperBound="-1"
        eType="#//TypeIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList1" upperBound="-1"
        eType="#//TypeIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idList2" upperBound="-1"
        eType="#//TypeIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//StatementContainer #//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abort" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbortInstance" eSuperTypes="#//StatementContainer #//AbortBody #//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCase" eSuperTypes="#//AbortBody #//WeakAbortBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//AbortCaseSingle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortCaseSingle" eSuperTypes="#//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="optEnd" eType="#//WeakAbortEndAlt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortEndAlt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Await" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//AwaitBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitInstance" eSuperTypes="#//StatementContainer #//AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwaitCase" eSuperTypes="#//AwaitBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//AbortCaseSingle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcCall" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proc" eType="#//Procedure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varList" unique="false"
        upperBound="-1" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Do" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoUpto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatching">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DoWatchingEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoWatchingEnd" eSuperTypes="#//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emit" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EveryDo" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exit" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="#//TrapDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Halt" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfTest" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//ThenPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsif" upperBound="-1"
        eType="#//ElsIf" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//ElsePart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElsIf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThenPart" eSuperTypes="#//StatementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElsePart" eSuperTypes="#//StatementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//LoopBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end1" eType="#//EndLoop"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//LoopEach"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndLoop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOpt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopEach"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopDelay" eSuperTypes="#//LoopEach">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBody" eSuperTypes="#//StatementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nothing" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Present" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//PresentBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//ElsePart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEventBody" eSuperTypes="#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//PresentEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" eType="#//ThenPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCaseList" eSuperTypes="#//PresentBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//PresentCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentCase" eSuperTypes="#//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//PresentEvent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ModuleRenaming"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//RenamingList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenamingList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//Renaming"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Renaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="renamings" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newType" eType="ecore:EEnum ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newFunc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcedureRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Procedure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Procedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalRenaming">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newName" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldName" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Suspend" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="#//DelayExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sustain" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trap" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDeclList" eType="#//TrapDeclList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapHandler" upperBound="-1"
        eType="#//TrapHandler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDeclList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapDecls" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapHandler" eSuperTypes="#//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trapExpr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//InterfaceVariableDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//DelayEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImmediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exec" eSuperTypes="#//StatementContainer #//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExecBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retSignal" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execCaseList" upperBound="-1"
        eType="#//ExecCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" unique="false" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//IVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecCase" eSuperTypes="#//StatementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ExecBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retSignal" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsterelTypeIdentifier" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//TypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="func" eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsterelType" eSuperTypes="#//TypeIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="estType" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalSignal" eSuperTypes="#//LocalSignalList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//RelationDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//RelationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbort" eSuperTypes="#//Abort"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortInstance" eSuperTypes="#//AbortInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//WeakAbortEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakAbortCase" eSuperTypes="#//AbortCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//WeakAbortEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapDecl" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrapExpression" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trap" eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ISignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionExpression" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kexpressions" upperBound="-1"
        eType="ecore:EClass ../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExpression" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="#//Constant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrapReferenceExpr" eSuperTypes="../../../../../../../de.cau.cs.kieler.core.kexpressions/model/kexpressions.ecore#//ValuedObjectReference"/>
</ecore:EPackage>
