<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evaluationresult"
    nsURI="http://www.eclipse.org/evaluationresult" nsPrefix="evaluationresult">
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationResult">
    <eOperations name="getConcreteModel" lowerBound="1" eType="ecore:EClass ../../org.eclipse.featuremodel.metamodel/models/featuremodel.ecore#//FeatureModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//ID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="success" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variantModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.featuremodel.metamodel/models/variantmodel.ecore#//VariantModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selections" upperBound="-1"
        eType="#//ResultSelection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluator" lowerBound="1"
        eType="#//IEvaluator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ID" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultSelection" eSuperTypes="../../org.eclipse.featuremodel.metamodel/models/variantmodel.ecore#//FeatureSelection">
    <eOperations name="getResult" lowerBound="1" eType="#//EvaluationResult"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IEvaluator" instanceClassName="org.eclipse.featuremodel.evaluation.IEvaluator"/>
</ecore:EPackage>
