<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_SyvzMVXWEeKA3c-tf3UAHQ"
    name="org" nsURI="http://example-ecore/1.0" nsPrefix="example-ecore">
  <eSubpackages xmi:id="_SyvzMlXWEeKA3c-tf3UAHQ" name="eclipse">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Tklf0FXWEeKA3c-tf3UAHQ" name="c1">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_VltqEFXWEeKA3c-tf3UAHQ" name="c2"
        eSuperTypes="#_Tklf0FXWEeKA3c-tf3UAHQ">
      <eStructuralFeatures xsi:type="ecore:EReference" name="aReference" eType="#_Tklf0FXWEeKA3c-tf3UAHQ"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
