<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="family" nsURI="http://family/1.0" nsPrefix="family">
  <eAnnotations source="EAnnotation0"/>
  <eClassifiers xsi:type="ecore:EClass" name="person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPR" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spouse" eType="#//person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrollment" upperBound="-1"
        eType="#//university"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="university">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" eType="#//Family"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Members" eType="#//person"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
