<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FCM"
    nsURI="http://papyrus/FCMProfile/1" nsPrefix="FCM">
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The template parameters list defines the parameters that are passed to the Acceleo template. If empty, the formal parameter list of the package template is used."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateParams" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Element" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" unique="false"
        lowerBound="1" eType="#//TemplateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualChoice" ordered="false"
        unique="false" eType="#//ActualChoice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemplateKind">
    <eLiterals name="PassFormal"/>
    <eLiterals name="LoopOperations" value="1"/>
    <eLiterals name="LoopProperty" value="2"/>
    <eLiterals name="Accumulate" value="3"/>
    <eLiterals name="LoopLiterals" value="4"/>
    <eLiterals name="LateEvaluation" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="LateEvaluation is more a tempalte binding rather than a template definition. In"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LoopPorts" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActualChoice">
    <eLiterals name="PassActual"/>
    <eLiterals name="InterfaceOfPPort" value="1"/>
    <eLiterals name="InterfaceOfRport" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This stereotype indicuates that the attribute does not only store values but needs to be configured initially be the user. It corresponds to the automatic creation of an entry  (slot+nstance specification) in the deployment plan "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A group of interaction components should apply both stereotypes. Each member of such a group must be an interaction component, but this is not enforced by the meta-model"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerRule" ordered="false"
        unique="false" upperBound="-1" eType="#//ContainerRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagateRule" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forConfig" ordered="false"
        upperBound="-1" eType="#//ConfigOption"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigOption">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Singleton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forDistribution" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPattern" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Collaboration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortKind">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedPort" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//ConfigurableElementInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" ordered="false" unique="false"
        eType="#//PortKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conjugated" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurableElementInstance" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" ordered="false"
        unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//ConfigurableElementInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ic" ordered="false" unique="false"
        eType="#//InteractionComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainInstance" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Element" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompImplTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateDefs" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterceptionKind">
    <eLiterals name="InterceptSomePorts"/>
    <eLiterals name="InterceptAllPorts" value="1"/>
    <eLiterals name="InterceptAllOutPorts" value="2"/>
    <eLiterals name="InterceptAllInPorts" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CppLibrary" eSuperTypes="#//ExternalLibrary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macros" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libs" ordered="false" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libPaths" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includePaths" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaLibrary" eSuperTypes="#//ExternalLibrary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classPath" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeRAM" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedOS" ordered="false"
        unique="false" upperBound="-1" eType="#//OperatingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arch" ordered="false" unique="false"
        upperBound="-1" eType="#//TargetArchitecture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeROM" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedTargetArch" ordered="false"
        lowerBound="1" eType="#//TargetArchitecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configOptions" ordered="false"
        upperBound="-1" eType="#//ConfigOption"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentPlan" ordered="false"
        lowerBound="1" eType="#//DeploymentPlan"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterceptionRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interceptionKind" ordered="false"
        unique="false" lowerBound="1" eType="#//InterceptionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portSet" ordered="false"
        unique="false" upperBound="-1" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetArch" ordered="false"
        lowerBound="1" eType="#//TargetArchitecture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" ordered="false"
        upperBound="-1" eType="#//ConfigOption"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Node" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedOS" ordered="false"
        lowerBound="1" eType="#//OperatingSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availRAM" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availROM" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colocateWithPort" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoIndex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoIndexPerNode" eSuperTypes="#//AutoIndex"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitPrecedence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokeAfter" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokeBefore" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Slot" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" ordered="false"
        lowerBound="1" eType="#//Connector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedSignature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_TemplateSignature"
        ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateSignature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseSignature" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TemplateSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseInstanceConfigurator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurator" ordered="false"
        lowerBound="1" eType="#//InstanceConfigurator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceConfigurator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
</ecore:EPackage>
