<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="description"
    nsURI="http://description/1.0" nsPrefix="description">
  <eClassifiers xsi:type="ecore:EClass" name="FacetType" abstract="true">
    <eOperations name="getQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//FacetValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Facet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//FacetType"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//FacetValue" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeID" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//FacetValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentDescription" eSuperTypes="../../org.reuseware.coconut.repository/model/repository.ecore#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//Facet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="ecore:EClass ../../org.reuseware.coconut.fragment/model/fragment.ecore#//Fragment"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationState" eType="#//DerivationState"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DerivationState">
    <eLiterals name="REFRESH_ALL" value="1"/>
    <eLiterals name="REFRESH_DIRECT_FACETS" value="2"/>
    <eLiterals name="REFRESH_RULE_FACETS" value="4"/>
    <eLiterals name="REFRESH_SPECIAL_RULE_FACETS" value="8"/>
    <eLiterals name="UP_TO_DATE" value="16"/>
  </eClassifiers>
</ecore:EPackage>
