<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="patterns"
    nsURI="http://eclectic.org/frontend/patL" nsPrefix="ec_frontend_patL">
  <eClassifiers xsi:type="ecore:EClass" name="PatternSpecification" eSuperTypes="#//dep/TransformationDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//Pattern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="#//dep/LocatedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//PObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVariables" upperBound="-1"
        eType="#//POutputVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="POutputVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//PObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PObject" eSuperTypes="#//dep/Variable #//dep/LocatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//dep/ClassUse"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//PFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PFeature" abstract="true" eSuperTypes="#//dep/LocatedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PAttribute" eSuperTypes="#//PFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//dep/Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//dep/Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PReference" eSuperTypes="#//PFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//PObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionReference" eSuperTypes="#//PReference"/>
  <eSubpackages name="dep" nsURI="http://eclectic.org/frontend/dep" nsPrefix="ec_frontend_dep">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TransformationDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="TransformationDefinitionParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassUse"/>
    <eClassifiers xsi:type="ecore:EClass" name="Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  </eSubpackages>
</ecore:EPackage>
