<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="function" nsURI="http://www.xtext.org/function/Function" nsPrefix="function">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Start" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpWithDefinitions" eSuperTypes="#//Start"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exp" eSuperTypes="#//ExpWithDefinitions #//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//TerminalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" upperBound="-1"
        eType="#//TerminalExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//VariableDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functioncall" eType="#//FunctionCall"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathFunction" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathTwoArg" eSuperTypes="#//MathFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//TerminalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOneArg" eSuperTypes="#//MathFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDefinition" eSuperTypes="#//ExpWithDefinitions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinition" eSuperTypes="#//ExpWithDefinitions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//ExpInFun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Start">
    <eStructuralFeatures xsi:type="ecore:EReference" name="func" eType="#//FunctionDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramvalues" upperBound="-1"
        eType="#//ParamValues" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamValues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//VariableDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpInFun" eSuperTypes="#//TerminalExpressionInFun">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//TerminalExpressionInFun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionInFun" eSuperTypes="#//ExpInFun">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" upperBound="-1"
        eType="#//TerminalExpressionInFun" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalExpressionInFun">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathFunctionInFun" eSuperTypes="#//ExpInFun">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathTwoArgInFun" eSuperTypes="#//MathFunctionInFun">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//TerminalExpressionInFun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOneArgInFun" eSuperTypes="#//MathFunctionInFun"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//Start">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iftype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Exp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whentrue" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenfalse" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
