<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Games"
    nsURI="http://www.meekmok.com/Games" nsPrefix="games">
  <eClassifiers xsi:type="ecore:EClass" name="Profile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" lowerBound="1"
        eType="#//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Profiles">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profiles" upperBound="-1"
        eType="#//Profile"/>
  </eClassifiers>
</ecore:EPackage>
