<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="germplasm"
    nsURI="http:///org/generationcp/model/data/germplasm.ecore" nsPrefix="org.generationcp.model.data.germplasm">
  <eClassifiers xsi:type="ecore:EClass" name="BiologicalStatus" eSuperTypes="feature.ecore#//FeatureSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiologicalStatusCode" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clade" eSuperTypes="core.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Clade"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectedGermplasm" eSuperTypes="#//SourceGermplasm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectingMission" eType="#//CollectingMission"
        eOpposite="#//CollectingMission/collectedGermplasm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ethnobotany" eType="#//Ethnobotany"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collector" eType="ecore:EClass organization.ecore#//Contact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectingSite" eType="#//CollectingSite"
        eOpposite="#//CollectingSite/samples"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectingMission" eSuperTypes="core.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startDate" eType="ecore:EClass value.ecore#//TimeValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endDate" eType="ecore:EClass value.ecore#//TimeValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectingMissionPartners"
        upperBound="-1" eType="ecore:EClass organization.ecore#//Contact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectedGermplasm" lowerBound="1"
        upperBound="-1" eType="#//CollectedGermplasm" eOpposite="#//CollectedGermplasm/collectingMission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectingOrAcquisitionSourceCode" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectingSite" eSuperTypes="location.ecore#//SimpleLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="samples" lowerBound="1"
        upperBound="-1" eType="#//CollectedGermplasm" eOpposite="#//CollectedGermplasm/collectingSite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prevailingStresses" eType="ecore:EClass feature.ecore#//FeatureSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedFlora" eType="ecore:EClass feature.ecore#//FeatureSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivativeMethod" eSuperTypes="#//GermplasmMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivativeNeighbourhood" eSuperTypes="#//GermplasmNeighbourhood"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonatedGermplasm" eSuperTypes="#//FoundingGermplasm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donor" eType="ecore:EClass organization.ecore#//Contact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donorGermplasmIdentifier"
        eType="ecore:EClass identification.ecore#//Identifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ethnobotany" eSuperTypes="feature.ecore#//FeatureSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localUses" eType="ecore:EClass feature.ecore#//FeatureSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localGermplasmNames" eType="ecore:EClass identification.ecore#//IdentifierSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EthnobotanyCode" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="FoundingGermplasm" eSuperTypes="#//Germplasm"/>
  <eClassifiers xsi:type="ecore:EClass" name="FoundingGermplasmSet" eSuperTypes="#//GermplasmSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbourhood" eType="#//ManagementNeighbourhood"
        eOpposite="#//ManagementNeighbourhood/foundingGermplasmSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedGermplasm" eSuperTypes="#//SourceGermplasm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="breeder" eType="ecore:EClass organization.ecore#//Contact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerativeMethod" eSuperTypes="#//GermplasmMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenerativeNeighbourHood" eSuperTypes="#//GermplasmNeighbourhood"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneticMappingPopulation" eSuperTypes="#//ManagementNeighbourhood">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" eType="#//GenerativeNeighbourHood"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenomicStock" eSuperTypes="#//ManagementNeighbourhood"/>
  <eClassifiers xsi:type="ecore:EClass" name="Genus" eSuperTypes="#//TaxonRank"/>
  <eClassifiers xsi:type="ecore:EClass" name="Germplasm" eSuperTypes="core.ecore#//Entity">
    <eOperations name="getTaxon" lowerBound="1" eType="#//Taxon">
      <eParameters name="taxonomyLevel" eType="#//TaxonRank"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cropName" eType="ecore:EClass identification.ecore#//Identifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biologicalStatus" eType="#//BiologicalStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intellectualProperty" eType="ecore:EClass property.ecore#//IntellectualPropertyPortfolio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//GermplasmNeighbourhood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//GermplasmLocation" eOpposite="#//GermplasmLocation/germplasm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisitionDate" eType="ecore:EClass value.ecore#//TimeValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisitionSource" eType="#//CollectingOrAcquisitionSourceCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consensusGenotypes" upperBound="-1"
        eType="ecore:EClass genotype.ecore#//DetectedVariant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consensusPhenotypes" upperBound="-1"
        eType="ecore:EClass phenotype.ecore#//Phenotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmCollection" eSuperTypes="identification.ecore#//SimpleIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stocks" lowerBound="1"
        upperBound="-1" eType="#//GermplasmNeighbourhood" eOpposite="#//GermplasmNeighbourhood/germplasmCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//HoldingInstitute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmLocation" eSuperTypes="location.ecore#//SimpleLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="germplasm" eType="#//Germplasm"
        eOpposite="#//Germplasm/locations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmMethod" eSuperTypes="#//GermplasmRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmNeighbourhood" eSuperTypes="#//GermplasmSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="germplasmCollection" eType="#//GermplasmCollection"
        eOpposite="#//GermplasmCollection/stocks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceGermplasmSet" eType="#//SourceGermplasmSet"
        eOpposite="#//SourceGermplasmSet/neighbourhood"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmRelationship" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmSet" eSuperTypes="core.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Germplasm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creationDate" eType="ecore:EClass value.ecore#//TimeValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="ecore:EClass organization.ecore#//LegalEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmStudy" eSuperTypes="study.ecore#//Study">
    <eStructuralFeatures xsi:type="ecore:EReference" name="germplasm" eType="#//GermplasmSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="growthConditions" eType="ecore:EClass feature.ecore#//FeatureSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatments" eType="ecore:EClass feature.ecore#//FeatureSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GermplasmType" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="GrowthCondition" eSuperTypes="study.ecore#//Factor"/>
  <eClassifiers xsi:type="ecore:EClass" name="HoldingInstitute" eSuperTypes="organization.ecore#//Organization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" lowerBound="1"
        upperBound="-1" eType="#//GermplasmCollection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsolatedGermplasm" eSuperTypes="#//FoundingGermplasm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceGermplasm" eType="#//SourceGermplasm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceMethod" eSuperTypes="#//GermplasmMethod"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaintenanceNeighbourhood" eSuperTypes="#//GermplasmNeighbourhood"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementNeighbourhood" eSuperTypes="#//MaintenanceNeighbourhood">
    <eStructuralFeatures xsi:type="ecore:EReference" name="foundingGermplasmSet" eType="#//FoundingGermplasmSet"
        eOpposite="#//FoundingGermplasmSet/neighbourhood"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementRelationship" eSuperTypes="#//GermplasmRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nursery" eSuperTypes="#//GermplasmStudy"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParentalBreedingMaterial" eSuperTypes="#//ManagementNeighbourhood"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlantOntologyTerm" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleClade" eSuperTypes="identification.ecore#//SimpleIdentifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tree" eType="ecore:EClass publication.ecore#//Content"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceGermplasm" eSuperTypes="#//Germplasm"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceGermplasmSet" eSuperTypes="#//GermplasmSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbourhood" eType="#//GermplasmNeighbourhood"
        eOpposite="#//GermplasmNeighbourhood/sourceGermplasmSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Species" eSuperTypes="#//TaxonRank"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subspecies" eSuperTypes="#//TaxonRank"/>
  <eClassifiers xsi:type="ecore:EClass" name="Taxon" eSuperTypes="#//Clade">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxonRank" eType="#//TaxonRank"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commonName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaxonRank" eSuperTypes="ontology.ecore#//SimpleOntologyTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="Treatment" eSuperTypes="#//GrowthCondition"/>
</ecore:EPackage>
