<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="googleanalytics" nsURI="http://www.soluvas.org/schema/web.googleanalytics/1.0"
    nsPrefix="googleanalytics">
  <eClassifiers xsi:type="ecore:EClass" name="GoogleAnalyticsManager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackingId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"/>
  </eClassifiers>
</ecore:EPackage>
