<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="js"
    nsURI="http://eclipselabs.org/mlang/js" nsPrefix="org.eclipselabs.mlang">
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="common.ecore#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true" eOpposite="#//Argument/function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass common.ecore#//Location"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass common.ecore#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        eOpposite="#//Function/arguments"/>
  </eClassifiers>
</ecore:EPackage>
