<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kompose"
    nsURI="http://kompose/1.0" nsPrefix="kompose">
  <eClassifiers xsi:type="ecore:EClass" name="Matcher"/>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="#//Modes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composedModelURI" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aspectModelURI" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryModelURI" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predirectivesPM" upperBound="-1"
        eType="ecore:EClass ../../kompose_directives_v1/metamodel/directives.ecore#//CompositionDirective"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predirectivesAM" upperBound="-1"
        eType="ecore:EClass ../../kompose_directives_v1/metamodel/directives.ecore#//CompositionDirective"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postdirectives" upperBound="-1"
        eType="ecore:EClass ../../kompose_directives_v1/metamodel/directives.ecore#//CompositionDirective"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merger"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engine" lowerBound="1"
        eType="#//Engine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="merger" lowerBound="1"
        eType="#//Merger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matcher" lowerBound="1"
        eType="#//Matcher"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Modes">
    <eLiterals name="UNION"/>
    <eLiterals name="INTERSECTION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConflictResolver"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Match"/>
</ecore:EPackage>
