<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="meta"
    nsURI="http://abstratt.com/mdd/1.0.0/meta" nsPrefix="meta">
  <eClassifiers xsi:type="ecore:EClass" name="MetaValueSpecification" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" &#xD;&#xA;  A value specification that can return references to elements. &#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaValue" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionAction" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Action">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" &#xD;&#xA;  A conversion action that can cast one value from one classifier to another. &#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InputPin"
        containment="true">
      <eAnnotations source="subsets" references="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Action/input"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//OutputPin"
        containment="true">
      <eAnnotations source="subsets" references="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Action/output"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicCallBehaviorAction" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//CallAction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" &#xD;&#xA;  A call action that can invoke a behavior reference that is defined at runtime. &#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InputPin"
        containment="true">
      <eAnnotations source="subsets" references="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Action/input"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" A signature is a classifier with parameters. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"
        containment="true">
      <eAnnotations source="subsets" references="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Namespace/member"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Closure" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" A closure is a special kind of activity that has another activity's &#xD;&#xA;   activity node as context.&#xD;&#xA; "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextActivityNode" ordered="false"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StructuredActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" &#xD;&#xA;    The activity node that provides context to this closure. &#xD;&#xA;    The closure might reference variables declared in the context&#xD;&#xA;    activity node.&#xD;&#xA;  "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteral" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
