<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mipsimulator" nsURI="http://mipsimulator/1.0" nsPrefix="mipsimulator">
  <eSubpackages name="PC">
    <eClassifiers xsi:type="ecore:EClass" name="PC">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_pcValue " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCAddUnit">
      <eOperations name="incrementProgramCounter() : void"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TO_NEXT_INS" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_currentPCValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ALU">
    <eClassifiers xsi:type="ecore:EClass" name="ALU">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_inputReadData1" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_inputReadData2" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_outputAluResult" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_outputZero " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ALUControl"/>
  </eSubpackages>
  <eSubpackages name="Memory">
    <eClassifiers xsi:type="ecore:EClass" name="InstructionMemory">
      <eOperations name="initialize() : void"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_memory" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataMemory">
      <eOperations name="initialize() : void"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_memory" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_inputAddress" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_inputWriteData" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_outputReadData" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Registers"/>
  </eSubpackages>
  <eSubpackages name="Register">
    <eClassifiers xsi:type="ecore:EClass" name="Registers">
      <eOperations name="initialize() : void"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_symbolicNames" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_numericRepresentation"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_readReg1" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_readReg2" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_writeReg" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_writeData" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_readData1" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_readData2" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Controls">
    <eClassifiers xsi:type="ecore:EClass" name="Control">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_regDist" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_branch" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_memRead" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_memToReg" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_aluOp0" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_memWrite" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_aluSrc" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_regWrite" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_aluOp1" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="gui"/>
  <eSubpackages name="controller"/>
  <eSubpackages name="Parser">
    <eClassifiers xsi:type="ecore:EClass" name="Parser"/>
  </eSubpackages>
</ecore:EPackage>
