<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
	name="events" nsURI="http://org/mmiEventsModel" nsPrefix="events">
	<eClassifiers xsi:type="ecore:EClass" name="Event"
		abstract="true">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
			defaultValueLiteral="0" />
	</eClassifiers>

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="InputEvent"
		abstract="true" eSuperTypes="#//Event" />
	<eClassifiers xsi:type="ecore:EClass" name="OutputEvent"
		abstract="true" eSuperTypes="#//Event"/>
	<eClassifiers xsi:type="ecore:EClass" name="DialogueContentEvent"
		abstract="true" eSuperTypes="#//Event">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="nitems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="MetacommEvent"
		abstract="true" eSuperTypes="#//Event" />
	<eClassifiers xsi:type="ecore:EClass" name="TurnControlEvent"
		abstract="true" eSuperTypes="#//Event" />
	<eClassifiers xsi:type="ecore:EClass" name="TurnTimingEvent"
		abstract="true" eSuperTypes="#//Event" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="NavigationEvent"
		abstract="true" eSuperTypes="#//InputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="TextEvent"
		abstract="true" eSuperTypes="#//InputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="SpeechInputEvent"
		abstract="true" eSuperTypes="#//InputEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

<eClassifiers xsi:type="ecore:EClass" name="ScreenEvent"
      abstract="true" eSuperTypes="#//OutputEvent"/>
      
	<eClassifiers xsi:type="ecore:EClass" name="ScreenContentEvent"
		abstract="true" eSuperTypes="#//ScreenEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nitems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   
	<eClassifiers xsi:type="ecore:EClass" name="SpeechOutputEvent"
		abstract="true" eSuperTypes="#//OutputEvent" />
		
   <eClassifiers xsi:type="ecore:EClass" name="SpeechOutputContentEvent"
      abstract="true" eSuperTypes="#//SpeechOutputEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nitems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="TouchEvent"
		eSuperTypes="#//NavigationEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="ClickEvent"
		eSuperTypes="#//NavigationEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="LongClickEvent"
		eSuperTypes="#//NavigationEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="ScrollEvent"
		eSuperTypes="#//NavigationEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="MoveEvent"
		eSuperTypes="#//NavigationEvent">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
	</eClassifiers>
	
	
	<eClassifiers xsi:type="ecore:EClass" name="NavigationMoveEvent"
		eSuperTypes="#//NavigationEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="NavigationActionEvent"
		eSuperTypes="#//NavigationEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NavigationExploreEvent"
		eSuperTypes="#//NavigationEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="KeyTextEvent"
		eSuperTypes="#//TextEvent">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="KeyExploreEvent"
		eSuperTypes="#//TextEvent">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="KeyCommandEvent"
		eSuperTypes="#//TextEvent">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="TextWordEvent"
		eSuperTypes="#//TextEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="TextExploreEvent"
		eSuperTypes="#//TextEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="TextCommandEvent"
		eSuperTypes="#//TextEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="GuiElementsEvent"
		eSuperTypes="#//ScreenContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="GuiFeedbackEvent"
      eSuperTypes="#//ScreenContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="GuiConceptsEvent"
      eSuperTypes="#//ScreenContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="GuiNoiseEvent"
      eSuperTypes="#//ScreenContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="GuiQuestionsEvent"
      eSuperTypes="#//ScreenContentEvent" />
      
      <!-- -->
   <!-- -->
   <!-- -->

   <eClassifiers xsi:type="ecore:EClass" name="SpeechElementsEvent"
      eSuperTypes="#//SpeechOutputContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="SpeechFeedbackEvent"
      eSuperTypes="#//SpeechOutputContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="SpeechConceptsEvent"
      eSuperTypes="#//SpeechOutputContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="SpeechNoiseEvent"
      eSuperTypes="#//SpeechOutputContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="SpeechQuestionsEvent"
      eSuperTypes="#//SpeechOutputContentEvent" />


	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="CorrectAnswerEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="IncorrectAnswerEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="PartiallyCorrectAnswerEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NotAnswerEvent"
		eSuperTypes="#//SpeechOutputEvent" />

	<eClassifiers xsi:type="ecore:EClass" name="OpenPromptEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="HalfOpenPromptEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="ClosedPromptEvent"
		eSuperTypes="#//SpeechOutputEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NoQuestionPromptEvent"
		eSuperTypes="#//SpeechOutputEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="OverallWordsEvent"
		eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nwords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="SubstitutedWordsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nwords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="DeletedWordsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nwords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="InsertedWordsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nwords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   

   <eClassifiers xsi:type="ecore:EClass" name="OverallSentencesEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nsentences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="SubstitutedSentencesEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nsentences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="DeletedSentencesEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nsentences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="InsertedSentencesEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nsentences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   

   <eClassifiers xsi:type="ecore:EClass" name="OverallConceptsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nconcepts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="SubstitutedConceptsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nconcepts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="DeletedConceptsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nconcepts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   <eClassifiers xsi:type="ecore:EClass" name="InsertedConceptsEvent"
      eSuperTypes="#//SpeechInputEvent" >
      <eStructuralFeatures xsi:type="ecore:EAttribute"
         name="nconcepts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
   </eClassifiers>
   
   
   
   
   <eClassifiers xsi:type="ecore:EClass" name="CorrectlyParsedUtteranceEvent"
      eSuperTypes="#//SpeechInputEvent" />
      <eClassifiers xsi:type="ecore:EClass" name="PartiallyParsedUtteranceEvent"
      eSuperTypes="#//SpeechInputEvent" />
      <eClassifiers xsi:type="ecore:EClass" name="IncorrectlyParsedUtteranceEvent"
      eSuperTypes="#//SpeechInputEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="NewElementsEvent"
		eSuperTypes="#//DialogueContentEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NewFeedbackElementsEvent"
		eSuperTypes="#//DialogueContentEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NewConceptsEvent"
		eSuperTypes="#//DialogueContentEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="NewNoiseEvent"
		eSuperTypes="#//DialogueContentEvent" />
   <eClassifiers xsi:type="ecore:EClass" name="NewQuestionsEvent"
      eSuperTypes="#//DialogueContentEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="HelpTurnEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="CorrectionTurnEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="CancelTurnEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="RestartTurnEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="BargeinEvent"
		eSuperTypes="#//MetacommEvent">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="successful"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="DIVRejectionEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="ASRRejectionEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="GRRejectionEvent"
		eSuperTypes="#//MetacommEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="TimeoutEvent"
		eSuperTypes="#//MetacommEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="AppStartEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="AppEndEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="StartDialogueEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="EndDialogueEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="StartSystemTurnEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="EndSystemTurnEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="StartUserTurnEvent"
		eSuperTypes="#//TurnControlEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="EndUserTurnEvent"
		eSuperTypes="#//TurnControlEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EClass" name="SystemFeedbackStartEvent"
		eSuperTypes="#//TurnTimingEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="SystemActionStartEvent"
		eSuperTypes="#//TurnTimingEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="SystemActionEndEvent"
		eSuperTypes="#//TurnTimingEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="UserFeedbackStartEvent"
		eSuperTypes="#//TurnTimingEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="UserActionStartEvent"
		eSuperTypes="#//TurnTimingEvent" />
	<eClassifiers xsi:type="ecore:EClass" name="UserActionEndEvent"
		eSuperTypes="#//TurnTimingEvent" />

	<!-- -->
	<!-- -->
	<!-- -->

	<eClassifiers xsi:type="ecore:EEnum" name="event_t">

		<!-- Gui Navigation Input (low and high level) -->

		<eLiterals name="TOUCH" value="101" />
		<eLiterals name="CLICK" value="102" />
		<eLiterals name="LONGCLICK" value="103" />
		<eLiterals name="ITEMCLICK" value="104" />
		<eLiterals name="ITEMLONGCLICK" value="105" />
		<eLiterals name="SCROLL" value="106" />
		<eLiterals name="MOVE" value="107" />
		<eLiterals name="NAVIGATIONMOVE" value="1001" />
		<eLiterals name="NAVIGATIONLENGTH" value="1002" />
		<eLiterals name="NAVIGATIONACTION" value="1003" />
		<eLiterals name="NAVIGATIONEXPLORE" value="1004" />

		<!-- Gui Text Input (low and high level) -->

		<eLiterals name="KEYTEXT" value="201" />
		<eLiterals name="KEYEXPLORE" value="202" />
		<eLiterals name="KEYCOMMAND" value="203" />
		<eLiterals name="TEXTWORD" value="2001" />
		<eLiterals name="TEXTEXPLORE" value="2002" />
		<eLiterals name="TEXTCOMMAND" value="2003" />
		
		<!-- Speech input (high level) -->

      <eLiterals name="OVERALLWORDS" value="7001" />
      <eLiterals name="SUBSTITUTEDWORDS" value="7002" />
      <eLiterals name="DELETEDWORDS" value="7003" />
      <eLiterals name="INSERTEDWORDS" value="7004" />
      
      <eLiterals name="OVERALLSENTENCES" value="7005" />
      <eLiterals name="SUBSTITUTEDSENTENCES" value="7006" />
      <eLiterals name="DELETEDSENTENCES" value="7007" />
      <eLiterals name="INSERTEDSENTENCES" value="7008" />
      
      <eLiterals name="OVERALLCONCEPTS" value="7009" />
      <eLiterals name="SUBSTITUTEDCONCEPTS" value="7010" />
      <eLiterals name="DELETEDCONCEPTS" value="7011" />
      <eLiterals name="INSERTEDCONCEPTS" value="7012" />
      
      
      <eLiterals name="CORRECTLYPARSEDUTTERANCE" value="7013" />
      <eLiterals name="PARTIALLYPARSEDUTTERANCE" value="7014" />
      <eLiterals name="INCORRECTLYPARSEDUTTERANCE" value="7015" />
		
		<!-- Gui output (low level) -->

      <eLiterals name="GUIELEMENTS" value="401" />
      <eLiterals name="GUIFEEDBACK" value="402" />
      <eLiterals name="GUICONCEPTS" value="403" />
      <eLiterals name="GUINOISE" value="404" />
      <eLiterals name="GUIQUESTIONS" value="405" />
      
      <!-- Speech output (low level) -->

      <eLiterals name="SPEECHELEMENTS" value="411" />
      <eLiterals name="SPEECHFEEDBACK" value="412" />
      <eLiterals name="SPEECHCONCEPTS" value="413" />
      <eLiterals name="SPEECHNOISE" value="414" />
      <eLiterals name="SPEECHQUESTIONS" value="414" />

		<!-- General output (high level) -->

		<eLiterals name="NEWELEMENTS" value="4001" />
		<eLiterals name="NEWFEEDBACKELEMENTS" value="4002" />
		<eLiterals name="NEWCONCEPTS" value="4003" />
		<eLiterals name="NEWNOISE" value="4004" />
		<eLiterals name="NEWQUESTIONS" value="4005" />

		<!-- Metacommunication (high level) -->

		<eLiterals name="HELPTURN" value="5002" />
		<eLiterals name="CORRECTIONTURN" value="5003" />
		<eLiterals name="TIMEOUT" value="5004" />
		<eLiterals name="CANCELTURN" value="5005" />
		<eLiterals name="RESTARTTURN" value="5006" />
		<eLiterals name="BARGEIN" value="5007" />
		<eLiterals name="DIVREJECTION" value="5008" />
		<eLiterals name="ASRREJECTION" value="5009" />
		<eLiterals name="GRREJECTION" value="5010" />

		<!-- Speech output (high level) -->

		<eLiterals name="CORRECTANSWER" value="6001" />
		<eLiterals name="INCORRECTANSWER" value="6002" />
		<eLiterals name="PARTIALLYCORRECTANSWER" value="6003" />
		<eLiterals name="NOTANSWER" value="6004" />

		<eLiterals name="OPENPROMPT" value="6005" />
		<eLiterals name="HALFOPENPROMPT" value="6006" />
		<eLiterals name="CLOSEDPROMPT" value="6007" />
		<eLiterals name="NOQUESTIONPROMPT" value="6008" />

      

		<!-- Turn timing (low and high level) -->

		<eLiterals name="APPSTART" value="901" />
		<eLiterals name="APPEND" value="902" />
		<eLiterals name="STARTDIALOGUE" value="9001" />
		<eLiterals name="ENDDIALOGUE" value="9002" />

		<eLiterals name="STARTSYSTEMTURN" value="9003" />
		<eLiterals name="SYSTEMFEEDBACKSTART" value="9004" />
		<eLiterals name="SYSTEMACTIONSTART" value="9005" />
		<eLiterals name="SYSTEMACTIONEND" value="9006" />
		<eLiterals name="ENDSYSTEMTURN" value="9007" />

		<eLiterals name="STARTUSERTURN" value="9008" />
		<eLiterals name="USERFEEDBACKSTART" value="9009" />
		<eLiterals name="USERACTIONSTART" value="9010" />
		<eLiterals name="USERACTIONEND" value="9011" />
		<eLiterals name="ENDUSERTURN" value="9012" />
	</eClassifiers>
</ecore:EPackage>
