<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modulemap"
    nsURI="http:///modulemap.ecore" nsPrefix="modulemap">
  <eClassifiers xsi:type="ecore:EClass" name="ModuleMapping">
    <eReferences name="module" eType="ecore:EClass ../../com.ibm.etools.j2ee.core/rose/application.ecore#//Module"
        lowerBound="1"/>
    <eAttributes name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EARProjectMap">
    <eReferences name="mappings" eType="#//ModuleMapping" upperBound="-1" containment="true"/>
    <eReferences name="utilityJARMappings" eType="#//UtilityJARMapping" lowerBound="1"
        upperBound="-1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UtilityJARMapping">
    <eAttributes name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eAttributes name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
