<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nano"
    nsURI="http://www.huberlin.de/Nano" nsPrefix="nano">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="setupSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SetupSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//UnitSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//CodeSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//StructureSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SimulationSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcesSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SourcesSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorsSec" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//MonitorsSec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeSec2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//CodeSec"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetupSec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Instance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitSec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthUnit" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LengthUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequencyUnit" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//FrequencyUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lossUnit" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LossUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeSec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeBlock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LengthUnit">
    <eLiterals name="nanometer" literal="nanometers"/>
    <eLiterals name="microns" value="1" literal="microns"/>
    <eLiterals name="mm" value="2" literal="mm"/>
    <eLiterals name="cm" value="3" literal="cm"/>
    <eLiterals name="meters" value="4" literal="meters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="femto" literal="femtoseconds"/>
    <eLiterals name="pico" value="1" literal="picoseconds"/>
    <eLiterals name="nano" value="2" literal="nanoseconds"/>
    <eLiterals name="micro" value="3" literal="microseconds"/>
    <eLiterals name="milli" value="4" literal="milliseconds"/>
    <eLiterals name="seconds" value="5" literal="seconds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FrequencyUnit">
    <eLiterals name="hertz" literal="hertz"/>
    <eLiterals name="khz" value="1" literal="kilohertz"/>
    <eLiterals name="mhz" value="2" literal="megahertz"/>
    <eLiterals name="ghz" value="3" literal="gigahertz"/>
    <eLiterals name="thz" value="4" literal="terahertz"/>
    <eLiterals name="inverse" value="5" literal="inverse cm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LossUnit">
    <eLiterals name="permicron" literal="dB per micron"/>
    <eLiterals name="permm" value="1" literal="dB per mm"/>
    <eLiterals name="percm" value="2" literal="dB per cm"/>
    <eLiterals name="permeter" value="3" literal="dB per meter"/>
    <eLiterals name="perkm" value="4" literal="dB per km"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate2D">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate3D">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate3DSlab">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Dimension"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructureSec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Material"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Objects"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="number" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filepath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedMaterial">
    <eLiterals name="etch" literal="etch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOperation">
    <eLiterals name="and" literal="AND"/>
    <eLiterals name="not" value="1" literal="NOT"/>
    <eLiterals name="xor" value="2" literal="XOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slab" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Slab"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lattice" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Lattice"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slab">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate3DSlab"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thickness" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lattice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latticeType" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LatticeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="holeRadiusToDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holeRadius" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitOperations" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//UnitOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LatticeType">
    <eLiterals name="cubical" literal="cubical"/>
    <eLiterals name="hexagonal" value="1" literal="hexagonal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delete" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Delete"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="move" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Move"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overwrite" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Overwrite"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineDirection">
    <eLiterals name="horizontal" literal="horizontal"/>
    <eLiterals name="vertical" value="1" literal="vertical"/>
    <eLiterals name="diagonalminus45" value="2" literal="diagonal-45"/>
    <eLiterals name="diagonalplus45" value="3" literal="diagonal+45"/>
    <eLiterals name="diagonalminus60" value="4" literal="diagonal-60"/>
    <eLiterals name="diagonalplus60" value="5" literal="diagonal+60"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineSelectionType">
    <eLiterals name="span" literal="span"/>
    <eLiterals name="length" value="1" literal="length"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="steps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="single" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SingleDelete"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineDelete"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//RangeDelete"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleDelete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineDelete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineSelectType" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineSelectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Step"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeDelete">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Move">
    <eStructuralFeatures xsi:type="ecore:EReference" name="single" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SingleMove"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineMove"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//RangeMove"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleMove">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineMove">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineSelectType" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineSelectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Step"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeMove">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Overwrite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="single" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//SingleOverwrite"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineOverwrite"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//RangeOverwrite"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleOverwrite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineOverwrite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineSelectType" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LineSelectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Step"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeOverwrite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate2D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate3D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="material2" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//PredefinedMaterial"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewElement" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element1" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logicoperation" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//LogicOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cuboid" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depth" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cone" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radiusGround" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="radiusTop" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sphere" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radius" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ring" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerRadius" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outerRadius" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thetaStart" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thetaStop" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pyramid" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSpanBottom" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ySpanBottom" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSpanTop" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ySpanTop" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationSec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bgIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dx" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dy" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dz" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xBoundary" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Boundaries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yBoundary" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Boundaries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zBoundary" eType="ecore:EEnum platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Boundaries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Boundaries">
    <eLiterals name="pml" literal="PML"/>
    <eLiterals name="symmetric" value="1" literal="Symmetric"/>
    <eLiterals name="antiSymmetric" value="2" literal="Anti-Symmetric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourcesSec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dipole" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Dipole"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BroadbandSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wavelengthCenter" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wavelengthSpan" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NarrowbandSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wavelength" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pulseLength" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pulseOffset" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dipole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate3D"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dipoleTheta" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dipolePhi" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broadbandSource" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//BroadbandSource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="narrowbandSource" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//NarrowbandSource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorsSec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Monitor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinate" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Coordinate3D"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calculation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value2" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binary" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthesis" eSuperTypes="platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass platform:/resource/de.huberlin.nanoworkbench2/src-gen/de/huberlin/nanoworkbench2/Nano.ecore#//Calculation"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
