<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nowarebicycleshop"
    nsURI="http://itu.nowarebicycleshop.schemes/nbs.ecore" nsPrefix="nbs">
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Part" abstract="true" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manufacturer" eType="#//Manufacturers"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frameType" eType="#//FrameType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wheel" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gear" abstract="true" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="InnerGear" eSuperTypes="#//Gear"/>
  <eClassifiers xsi:type="ecore:EClass" name="OuterGear" eSuperTypes="#//Gear"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pedals" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pedalType" eType="#//PedalTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Saddle" eSuperTypes="#//Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saddleType" eType="#//SaddleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HandBrakes" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="HandleBars" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Manufacturers">
    <eLiterals name="SuperParts"/>
    <eLiterals name="HomeParts" value="1"/>
    <eLiterals name="HandMadeParts" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FrameType">
    <eLiterals name="RacerFrame"/>
    <eLiterals name="CityFrame" value="1"/>
    <eLiterals name="UnicycleFrame" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="Red"/>
    <eLiterals name="Blue" value="1" literal="Blue"/>
    <eLiterals name="Black" value="2"/>
    <eLiterals name="Green" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SaddleType">
    <eLiterals name="RacingSaddle"/>
    <eLiterals name="ChildSaddle" value="1"/>
    <eLiterals name="SpecialUnicycleSaddle" value="2"/>
    <eLiterals name="ComfortSaddle" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PedalTypes">
    <eLiterals name="ChildPedals"/>
    <eLiterals name="SportsPedals" value="1" literal="Sports"/>
    <eLiterals name="ComfortPedals" value="2"/>
    <eLiterals name="ExtremePedals" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bicycle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customerData" upperBound="-1"
        eType="#//CustomerData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
