<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adviceobserverpattern"
    nsURI="http://reuseware.org/example/ecore/ObserverPattern" nsPrefix="org.reuseware.example.ecore">
  <eClassifiers xsi:type="ecore:EClass" name="Observer">
    <eOperations name="update" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" ordered="false"
        upperBound="-1" eType="#//Subject" eOpposite="#//Subject/observers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subject">
    <eOperations name="Attach" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="observer" lowerBound="1" eType="#//Observer"/>
    </eOperations>
    <eOperations name="Detach" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="observer" lowerBound="1" eType="#//Observer"/>
    </eOperations>
    <eOperations name="notify" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observers" upperBound="-1"
        eType="#//Observer" eOpposite="#//Observer/subjects"/>
  </eClassifiers>
</ecore:EPackage>
