<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="olark" nsURI="http://www.soluvas.org/schema/web.olark/1.0" nsPrefix="olark">
  <eClassifiers xsi:type="ecore:EClass" name="LiveChatManager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="siteId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" eType="#//LiveChatProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LiveChatProvider">
    <eLiterals name="olark"/>
    <eLiterals name="livechatinc" value="1"/>
  </eClassifiers>
</ecore:EPackage>
