<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="omadm"
    nsURI="http://www.eclipse.org/koneki/omadm/simulator/1.0" nsPrefix="omadm-sim">
  <eClassifiers xsi:type="ecore:EClass" name="OMADMSimulation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="#//Device" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="groupPathMustBeAValidPath&#xA;modelNameMustBeValid&#xA;customerPathMustBeAValidPath&#xA;deviceIdMustBeValid&#xA;rootNodeCategoryMustBeValid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceIdType" lowerBound="1"
        eType="#//DeviceIdType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tree" lowerBound="1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverUrl" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceIdType">
    <eLiterals name="FREE" literal="free"/>
    <eLiterals name="IMEI" value="1"/>
    <eLiterals name="MAC_ADDRESS" value="2" literal="MAC Address"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NodeFormat">
    <eLiterals name="CHR" literal="chr"/>
    <eLiterals name="B64" value="1" literal="b64"/>
    <eLiterals name="BIN" value="2" literal="bin"/>
    <eLiterals name="INT" value="3" literal="int"/>
    <eLiterals name="NODE" value="4" literal="node"/>
    <eLiterals name="NULL" value="5" literal="null"/>
    <eLiterals name="XML" value="6" literal="xml"/>
    <eLiterals name="DATE" value="7" literal="date"/>
    <eLiterals name="TIME" value="8" literal="time"/>
    <eLiterals name="FLOAT" value="9" literal="float"/>
    <eLiterals name="BOOL" value="10" literal="bool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nodeNameMustBeValid&#xA;nodeFormatMustBeValid&#xA;nodeTypeMustBeValid&#xA;nodeDataMustBeValid&#xA;nodeManagementMustBeValid&#xA;childrenMustBeAuthorized&#xA;childrenCategoryMustBeValid&#xA;childrenNameMustBeUnique&#xA;"/>
    </eAnnotations>
    <eOperations name="getPath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getRoot" lowerBound="1" eType="#//Node"/>
    <eOperations name="getRealGetManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealAddManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealDeleteManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealCopyManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealReplaceManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealExecManagement" lowerBound="1" eType="#//CommandManagement"/>
    <eOperations name="getRealGetCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getRealAddCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getRealDeleteCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getRealCopyCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getRealReplaceCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getRealExecCode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="isRoot" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isInterior" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isLeaf" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
        eType="#//NodeFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Node"
        eOpposite="#//Node/children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replaceManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="execManagement" lowerBound="1"
        eType="#//CommandManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replaceCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="execCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandManagement">
    <eLiterals name="INHERITED" literal="inherited"/>
    <eLiterals name="AUTOMATIC" value="1" literal="automatic"/>
    <eLiterals name="MANUAL" value="2" literal="manual"/>
    <eLiterals name="CONSTANT" value="3" literal="constant"/>
  </eClassifiers>
</ecore:EPackage>
