<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openome_model"
    nsURI="http:///edu/toronto/cs/openome_model.ecore" nsPrefix="edu.toronto.cs.openome_model">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_a" upperBound="-1" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_part_of" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="believes" upperBound="-1"
        eType="#//Belief"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plays" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occupies" upperBound="-1"
        eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ins" eType="#//Agent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndDecomposition" eSuperTypes="#//Decomposition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Intention"
        eOpposite="#//Intention/contributesFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        transient="true" eOpposite="#//Model/contributions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Intention"
        eOpposite="#//Intention/contributesTo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal_model_symmetry" eType="#//GoalModelingContributionSymmetry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Intention"
        eOpposite="#//Intention/decompositions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Intention"
        eOpposite="#//Intention/parentDecompositions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        transient="true" eOpposite="#//Model/decompositions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyFrom" eType="#//Dependable"
        eOpposite="#//Dependable/dependencyTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyTo" eType="#//Dependable"
        eOpposite="#//Dependable/dependencyFrom"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trust" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        transient="true" eOpposite="#//Model/dependencies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Intention"/>
  <eClassifiers xsi:type="ecore:EClass" name="Intention" eSuperTypes="#//Dependable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boundary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequential" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decompositions" upperBound="-1"
        eType="#//Decomposition" eOpposite="#//Decomposition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentDecompositions" upperBound="-1"
        eType="#//Decomposition" eOpposite="#//Decomposition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"
        transient="true" eOpposite="#//Container/intentions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/intentions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QualitativeReasoningCombinedLabel"
        eType="#//EvaluationLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QualitativeReasoningSatisfiedLabel"
        eType="#//EvaluationLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QualitativeReasoningDenialLabel"
        eType="#//EvaluationLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuantitativeReasoningCombinedLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuantitativeReasoningDeniedLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuantitativeReasoningSatisfiedLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesTo" upperBound="-1"
        eType="#//Contribution" eOpposite="#//Contribution/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesFrom" upperBound="-1"
        eType="#//Contribution" eOpposite="#//Contribution/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentions" upperBound="-1"
        eType="#//Intention" containment="true" resolveProxies="false" eOpposite="#//Intention/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//Contribution" containment="true" eOpposite="#//Contribution/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true" resolveProxies="false" eOpposite="#//Dependency/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decompositions" upperBound="-1"
        eType="#//Decomposition" containment="true" resolveProxies="false" eOpposite="#//Decomposition/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true" resolveProxies="false" eOpposite="#//Container/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correlations" upperBound="-1"
        eType="#//Correlation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrDecomposition" eSuperTypes="#//Decomposition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="covers" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Intention"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Softgoal" eSuperTypes="#//Intention">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Intention"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" eSuperTypes="#//Dependable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" upperBound="-1" eType="#//Actor"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentions" upperBound="-1"
        eType="#//Intention" containment="true" resolveProxies="false" eOpposite="#//Intention/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        transient="true" eOpposite="#//Model/containers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationTo" upperBound="-1"
        eType="#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationFrom" upperBound="-1"
        eType="#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Belief" eSuperTypes="#//Intention"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EvaluationLabel">
    <eLiterals name="None"/>
    <eLiterals name="Unknown"/>
    <eLiterals name="Satisfied"/>
    <eLiterals name="WeaklySatisfied"/>
    <eLiterals name="Denied"/>
    <eLiterals name="WeaklyDenied"/>
    <eLiterals name="Conflict"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GoalModelingContributionType">
    <eLiterals name="None" literal=""/>
    <eLiterals name="PlusPlus" value="1" literal="++"/>
    <eLiterals name="Plus" value="2" literal="+"/>
    <eLiterals name="Minus" value="3" literal="-"/>
    <eLiterals name="MinusMinus" value="4" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GoalModelingContributionSymmetry">
    <eLiterals name="Both" value="2"/>
    <eLiterals name="Sat"/>
    <eLiterals name="Den" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Correlation" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Intention"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Intention"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyFrom" upperBound="-1"
        eType="#//Dependency" eOpposite="#//Dependency/dependencyTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyTo" upperBound="-1"
        eType="#//Dependency" eOpposite="#//Dependency/dependencyFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelpContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Help"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HurtContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Hurt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Make"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Break"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SomePlusContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Some+"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SomeMinusContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Some-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="Unknown"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="AND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrContribution" eSuperTypes="#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contributionType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="OR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsAAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="ISA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoversAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Covers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsPartOfAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Is part of"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OccupiesAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Occupies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaysAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Plays"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INSAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="INS"/>
  </eClassifiers>
</ecore:EPackage>
