<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defs"
    nsURI="http://www.eclipse.org/NET4J/defs/1.0.0" nsPrefix="net4j.defs">
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorDef" abstract="true" eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bufferProvider" lowerBound="1"
        eType="#//BufferProviderDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executorService" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//ExecutorServiceDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negotiator" eType="ecore:EClass ../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//NegotiatorDef"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientProtocolProvider"
        lowerBound="1" upperBound="-1" eType="#//ClientProtocolFactoryDef" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClientProtocolFactoryDef" abstract="true"
      eSuperTypes="#//ProtocolProviderDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="TCPConnectorDef" eSuperTypes="#//ConnectorDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tcpSelectorDef" eType="#//TCPSelectorDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptorDef" abstract="true" eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bufferProvider" eType="#//BufferPoolDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executorService" eType="ecore:EClass ../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//ThreadPoolDef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negotiator" eType="ecore:EClass ../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//NegotiatorDef"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverProtocolProvider"
        lowerBound="1" upperBound="-1" eType="#//ServerProtocolFactoryDef" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCPAcceptorDef" eSuperTypes="#//AcceptorDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tcpSelectorDef" lowerBound="1"
        eType="#//TCPSelectorDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JVMAcceptorDef" eSuperTypes="#//AcceptorDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JVMConnectorDef" eSuperTypes="#//ConnectorDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPConnectorDef" eSuperTypes="#//ConnectorDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCPSelectorDef" eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerProtocolFactoryDef" abstract="true"
      eSuperTypes="#//ProtocolProviderDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="BufferProviderDef" abstract="true" eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def"/>
  <eClassifiers xsi:type="ecore:EClass" name="BufferPoolDef" eSuperTypes="#//BufferProviderDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolProviderDef" abstract="true"
      eSuperTypes="../../org.eclipse.net4j.util.defs/model/org.eclipse.net4j.util.defs.ecore#//Def"/>
</ecore:EPackage>
