<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinetDsl"
    nsURI="http://www.bomzhi.de/petrinet/PetrinetDsl" nsPrefix="petrinetDsl">
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Resource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Place"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Transaction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storages" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Storage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assureStatements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//AssureStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="takeStatements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//TakeStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="putStatements" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//PutStatement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssureStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TakeStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PutStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeRef" eType="ecore:EClass platform:/resource/de.bomzhi.petrinet/src-gen/de/bomzhi/petrinet/PetrinetDsl.ecore#//Place"/>
  </eClassifiers>
</ecore:EPackage>
