<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fr"
    nsURI="fr" nsPrefix="fr">
  <eSubpackages name="irisa" nsURI="http://www.irisa.fr/" nsPrefix="irisa">
    <eSubpackages name="triskell" nsURI="http://www.irisa.fr/triskell/" nsPrefix="triskell">
      <eSubpackages name="impactanalysis" nsURI="http://www.irisa.fr/triskell/impactanalysis"
          nsPrefix="ia">
        <eSubpackages name="pointcutmodel" nsURI="http://www.irisa.fr/triskell/impactanalysis/pointcutmodel"
            nsPrefix="pm">
          <eClassifiers xsi:type="ecore:EClass" name="PmProject">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
                eType="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement" containment="true"
                eOpposite="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement/project"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PmMethod" eSuperTypes="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="PmAspect" eSuperTypes="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="advisedElements"
                upperBound="-1" eType="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement"
                eOpposite="#//irisa/triskell/impactanalysis/pointcutmodel/PmElement/advisedBy"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="PmElement" abstract="true">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
                eType="#//irisa/triskell/impactanalysis/pointcutmodel/PmProject" eOpposite="#//irisa/triskell/impactanalysis/pointcutmodel/PmProject/elements"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="advisedBy" upperBound="-1"
                eType="#//irisa/triskell/impactanalysis/pointcutmodel/PmAspect" eOpposite="#//irisa/triskell/impactanalysis/pointcutmodel/PmAspect/advisedElements"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
