<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="propsheet"
    nsURI="http://www.eclipse.org/gmf/2008/GmfGraph/PropSheet" nsPrefix="propsheet">
  <eClassifiers xsi:type="ecore:EClass" name="PropertySectionContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customSections" upperBound="-1"
        eType="#//CustomPropertySection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomPropertySection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.gmf.formtk/model/binding.ecore#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/gmf/2009/GenModel#//GenCustomPropertyTab"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/gmf/2009/GenModel#//GenNode"/>
  </eClassifiers>
</ecore:EPackage>
