<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="q7dsl"
    nsURI="http://www.example.org/my/dsl" nsPrefix="q7dsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="advices" upperBound="-1"
        eType="#//Advice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Advice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="how" eType="#//How" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="who" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//When" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="why" eType="#//Why" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="what" eType="#//What" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whom" eType="#//Who" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="howmuch" eType="#//HowMuchRules"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Who">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" eType="#//Actor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="When">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Why">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="What">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Where">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" eType="#//What"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Why" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="How">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//DecompositionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enrich" eType="#//Enrichment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advices" upperBound="-1"
        eType="#//Advice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HowMuchRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="howmuch" upperBound="-1"
        eType="#//HowMuch" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HowMuch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="strength" eType="#//FLOAT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="why" eType="#//Why" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="who" eType="#//Who" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trust" eType="#//FLOAT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="what" eType="#//What" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="#//LabelEnumerator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="den" eType="#//FLOAT" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sat" eType="#//FLOAT" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FLOAT">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Op">
    <eLiterals name="HELP" value="1"/>
    <eLiterals name="HELP2" value="2"/>
    <eLiterals name="HURT" value="3"/>
    <eLiterals name="HURT2" value="4"/>
    <eLiterals name="MAKE" value="5"/>
    <eLiterals name="MAKE2" value="6"/>
    <eLiterals name="BREAK" value="7"/>
    <eLiterals name="BREAK2" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DecompositionType">
    <eLiterals name="AND" value="1"/>
    <eLiterals name="AND1" value="2"/>
    <eLiterals name="OR" value="3"/>
    <eLiterals name="OR1" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enrichment">
    <eLiterals name="SEQUENTIAL" value="1"/>
    <eLiterals name="SEQUENTIAL1" value="2"/>
    <eLiterals name="PARALLEL" value="3"/>
    <eLiterals name="PARALLEL1" value="4"/>
    <eLiterals name="XOR" value="5"/>
    <eLiterals name="XOR1" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelEnumerator">
    <eLiterals name="FULLY_SATISFIED" value="1"/>
    <eLiterals name="PARTIALLY_SATISFIED" value="2"/>
    <eLiterals name="FULLY_DENIED" value="3"/>
    <eLiterals name="PARTIALLY_DENIED" value="4"/>
    <eLiterals name="CONFLICT" value="5"/>
    <eLiterals name="UNKNOWN" value="6"/>
  </eClassifiers>
</ecore:EPackage>
