<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qa"
    nsURI="platform:/resource/qa/model/qa.ecore" nsPrefix="qa">
  <eClassifiers xsi:type="ecore:EClass" name="QAContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="#//QAContainerOptions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question" eSuperTypes="#//QAPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correct" lowerBound="1"
        eType="#//Answer" containment="true" eOpposite="#//Answer/question"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="candidates" upperBound="-1"
        eType="#//Answer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextRules" upperBound="-1"
        eType="#//NextRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" eType="#//Question"
        eOpposite="#//Question/correct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextAnswer" eSuperTypes="#//Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberAnswer" eSuperTypes="#//Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsilon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YesNoAnswer" eSuperTypes="#//Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QATest" eSuperTypes="#//QAContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//QAPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QASection" eSuperTypes="#//QAContainer #//QAPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QAPart" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionAnswer" eSuperTypes="#//Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionAnswer" eSuperTypes="#//NumberAnswer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QAContainerOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revealAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NextRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//QAPart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
