<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtcorecst" nsURI="http://www.eclipse.org/qvt/0.9/QVTcoreCST"
    nsPrefix="qvtccs">
  <eClassifiers xsi:type="ecore:EClass" name="MappingCS" eSuperTypes="../../org.eclipse.qvtd.xtext.qvtcorebase/model/QVTcoreBaseCST.ecore#//AbstractMappingCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedMappings" ordered="false"
        upperBound="-1" eType="#//MappingCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.qvtd.pivot.qvtcore/model/QVTcore.ecore#//Mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelCS" eSuperTypes="../../org.eclipse.ocl.examples.xtext.base/model/BaseCST.ecore#//RootPackageCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.qvtd.xtext.qvtcorebase/model/QVTcoreBaseCST.ecore#//TransformationCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.qvtd.xtext.qvtcorebase/model/QVTcoreBaseCST.ecore#//QueryCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//MappingCS" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
