<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="report"
    nsURI="http://genericity/language/gcomponent/report" nsPrefix="gcomponent_report">
  <eClassifiers xsi:type="ecore:EClass" name="ReportElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ReportKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReportKind">
    <eLiterals name="WARNING"/>
    <eLiterals name="ERROR" value="1"/>
  </eClassifiers>
</ecore:EPackage>
