<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="saltCore"
    nsURI="saltCore" nsPrefix="saltCore">
  <eClassifiers xsi:type="ecore:EClass" name="SNode" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Node #//SAnnotatableElement #//SNamedElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement #//SMetaAnnotatableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sGraph" eType="#//SGraph"
        volatile="true" transient="true" derived="true" eOpposite="#//SGraph/sNodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sLayers" upperBound="-1"
        eType="#//SLayer" volatile="true" transient="true" derived="true" eOpposite="#//SLayer/sNodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SRelation" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Edge #//SAnnotatableElement #//SNamedElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement #//SMetaAnnotatableElement">
    <eOperations name="addSType">
      <eParameters name="sType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSource" eType="#//SNode"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sTarget" eType="#//SNode"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sGraph" eType="#//SGraph"
        volatile="true" transient="true" derived="true" eOpposite="#//SGraph/sRelations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sLayers" upperBound="-1"
        eType="#//SLayer" volatile="true" transient="true" derived="true" eOpposite="#//SLayer/sRelations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAnnotatableElement" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//LabelableElement">
    <eOperations name="addSAnnotation">
      <eParameters name="sAnnotation" eType="#//SAnnotation"/>
    </eOperations>
    <eOperations name="getSAnnotation" eType="#//SAnnotation">
      <eParameters name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createSAnnotation" eType="#//SAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="sValueType" eType="#//SDATATYPE"/>
    </eOperations>
    <eOperations name="createSAnnotation" eType="#//SAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sAnnotations" upperBound="-1"
        eType="#//SAnnotation" volatile="true" transient="true" derived="true" containment="true"
        eOpposite="#//SAnnotation/sAnnotatableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAnnotation" eSuperTypes="#//SAbstractAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sAnnotatableElement" eType="#//SAnnotatableElement"
        volatile="true" transient="true" eOpposite="#//SAnnotatableElement/sAnnotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SGraph" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Graph #//SNamedElement #//SAnnotatableElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement #//SMetaAnnotatableElement">
    <eOperations name="addSNode">
      <eParameters name="sNode" eType="#//SNode"/>
    </eOperations>
    <eOperations name="getSNode" eType="#//SNode">
      <eParameters name="sNodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addSRelation">
      <eParameters name="sRelation" eType="#//SRelation"/>
    </eOperations>
    <eOperations name="getSRelation" eType="#//SRelation">
      <eParameters name="sRelationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addSLayer">
      <eParameters name="sLayer" eType="#//SLayer"/>
    </eOperations>
    <eOperations name="getSLayer" eType="#//SLayer">
      <eParameters name="sLayerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSRoots" upperBound="-1" eType="#//SNode"/>
    <eOperations name="getSLeafs" upperBound="-1" eType="#//SNode"/>
    <eOperations name="traverse">
      <eParameters name="startSNodes" upperBound="-1" eType="#//SNode"/>
      <eParameters name="traverseType" eType="ecore:EEnum ../../../../../salt-graph/src/main/resources/model/graph.ecore#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//SGraphTraverseHandler"/>
    </eOperations>
    <eOperations name="traverse">
      <eParameters name="startSNodes" upperBound="-1" eType="#//SNode"/>
      <eParameters name="traverseType" eType="ecore:EEnum ../../../../../salt-graph/src/main/resources/model/graph.ecore#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//SGraphTraverseHandler"/>
      <eParameters name="isCycleSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getSLayerByName" upperBound="-1" eType="#//SLayer">
      <eParameters name="layerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sRelations" upperBound="-1"
        eType="#//SRelation" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//SRelation/sGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sNodes" upperBound="-1"
        eType="#//SNode" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//SNode/sGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sLayers" upperBound="-1"
        eType="#//SLayer" volatile="true" transient="true" derived="true" eOpposite="#//SLayer/sGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SNamedElement" eSuperTypes="#//SFeaturableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SIdentifiableElement" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sElementId" eType="#//SElementId"
        volatile="true" transient="true" derived="true" eOpposite="#//SElementId/sIdentifiableElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sElementPath" eType="#//URI"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="SProcessingAnnotation" eSuperTypes="#//SAbstractAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sProcessingAnnotatableElement"
        eType="#//SProcessingAnnotatableElement" volatile="true" transient="true"
        derived="true" eOpposite="#//SProcessingAnnotatableElement/sProcessingAnnotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SProcessingAnnotatableElement" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//LabelableElement">
    <eOperations name="addSProcessingAnnotation">
      <eParameters name="sProcessingAnnotation" eType="#//SProcessingAnnotation"/>
    </eOperations>
    <eOperations name="getSProcessingAnnotation" eType="#//SProcessingAnnotation">
      <eParameters name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createSProcessingAnnotation" eType="#//SProcessingAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="sValueType" eType="#//SDATATYPE"/>
    </eOperations>
    <eOperations name="createSProcessingAnnotation" eType="#//SProcessingAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sProcessingAnnotations"
        upperBound="-1" eType="#//SProcessingAnnotation" changeable="false" volatile="true"
        transient="true" derived="true" containment="true" eOpposite="#//SProcessingAnnotation/sProcessingAnnotatableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SElementId" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sIdentifiableElement" eType="#//SIdentifiableElement"
        volatile="true" transient="true" derived="true" eOpposite="#//SIdentifiableElement/sElementId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sElementPath" eType="#//URI"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFeature" eSuperTypes="#//SAbstractAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sFeaturableElement" eType="#//SFeaturableElement"
        volatile="true" transient="true" derived="true" eOpposite="#//SFeaturableElement/sFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFeaturableElement" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//LabelableElement">
    <eOperations name="addSFeature">
      <eParameters name="sFeature" eType="#//SFeature"/>
    </eOperations>
    <eOperations name="getSFeature" eType="#//SFeature">
      <eParameters name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSFeature" eType="#//SFeature">
      <eParameters name="sNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sFeatureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createSFeature" eType="#//SFeature">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="sValueType" eType="#//SDATATYPE"/>
    </eOperations>
    <eOperations name="createSFeature" eType="#//SFeature">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sFeatures" upperBound="-1"
        eType="#//SFeature" volatile="true" transient="true" derived="true" containment="true"
        eOpposite="#//SFeature/sFeaturableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMetaAnnotatableElement" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//LabelableElement">
    <eOperations name="addSMetaAnnotation">
      <eParameters name="sMetaAnnotation" eType="#//SMetaAnnotation"/>
    </eOperations>
    <eOperations name="getSMetaAnnotation" eType="#//SMetaAnnotation">
      <eParameters name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createSMetaAnnotation" eType="#//SMetaAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="sValueType" eType="#//SDATATYPE"/>
    </eOperations>
    <eOperations name="createSMetaAnnotation" eType="#//SMetaAnnotation">
      <eParameters name="sNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="sValueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sMetaAnnotations" upperBound="-1"
        eType="#//SMetaAnnotation" volatile="true" transient="true" derived="true"
        containment="true" eOpposite="#//SMetaAnnotation/sMetaAnnotatableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMetaAnnotation" eSuperTypes="#//SAbstractAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sMetaAnnotatableElement"
        eType="#//SMetaAnnotatableElement" volatile="true" transient="true" derived="true"
        eOpposite="#//SMetaAnnotatableElement/sMetaAnnotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAbstractAnnotation" abstract="true"
      eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Label">
    <eOperations name="getSValueSTEXT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getSValueSBOOLEAN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="getSValueSNUMERIC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eOperations name="getSValueSFLOAT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eOperations name="getSValueSURI" eType="#//URI"/>
    <eOperations name="getSValueSOBJECT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SNS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SValueType" eType="#//SDATATYPE"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SDATATYPE">
    <eLiterals name="STEXT"/>
    <eLiterals name="SBOOLEAN" value="1"/>
    <eLiterals name="SNUMERIC" value="2"/>
    <eLiterals name="SFLOAT" value="3"/>
    <eLiterals name="SURI" value="4"/>
    <eLiterals name="SOBJECT" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLayer" eSuperTypes="../../../../../salt-graph/src/main/resources/model/graph.ecore#//Layer #//SNamedElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SAnnotatableElement #//SMetaAnnotatableElement #//SFeaturableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sRelations" upperBound="-1"
        eType="#//SRelation" volatile="true" transient="true" derived="true" eOpposite="#//SRelation/sLayers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sNodes" upperBound="-1"
        eType="#//SNode" volatile="true" transient="true" derived="true" eOpposite="#//SNode/sLayers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sGraph" eType="#//SGraph"
        volatile="true" transient="true" derived="true" eOpposite="#//SGraph/sLayers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSubLayers" upperBound="-1"
        eType="#//SLayer" volatile="true" transient="true" derived="true" eOpposite="#//SLayer/sSuperLayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSuperLayer" eType="#//SLayer"
        volatile="true" transient="true" derived="true" eOpposite="#//SLayer/sSubLayers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SGraphTraverseHandler" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.saltCore.SGraphTraverseHandler"/>
</ecore:EPackage>
