<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="http://ict-alive.sourceforge.net/owls/service"
    nsPrefix="service">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGrounding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="1"
        eType="#//Service" eOpposite="#//Service/supports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presents" upperBound="-1"
        eType="#//ServiceProfile" containment="true" eOpposite="#//ServiceProfile/presentedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="describedBy" eType="#//ServiceModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supports" eType="#//ServiceGrounding"
        containment="true" eOpposite="#//ServiceGrounding/supportedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedBy" upperBound="-1"
        eType="#//ServiceProvider" eOpposite="#//ServiceProvider/provides"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentedBy" eType="#//Service"
        eOpposite="#//Service/presents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
        eType="#//Service" eOpposite="#//Service/providedBy"/>
  </eClassifiers>
</ecore:EPackage>
