<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="shapes"
    nsURI="shapes" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shapes" upperBound="-1"
        eType="#//Shape" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//AbstractConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSketch" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.sketch.core/model/sketch.ecore#//Sketch"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="svg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square" eSuperTypes="#//Shape"/>
  <eClassifiers xsi:type="ecore:EClass" name="Triangle" eSuperTypes="#//Shape"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unknown" eSuperTypes="#//Shape">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dna" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="####"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="ecore:EClass ../../org.eclipse.sketch.core/model/sketch.ecore#//Sketch"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//AbstractConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DashedConnection" eSuperTypes="#//AbstractConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConnection" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Shape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Shape"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
