<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sitacview"
    nsURI="http://sitacview/1.0" nsPrefix="sitacview">
  <eClassifiers xsi:type="ecore:EClass" name="MoyenClipboard" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapWidget" eSuperTypes="#//View #//DragTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualZoomLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualLat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//MapItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//TitledView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selected" eType="#//TitledView"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View"/>
  <eClassifiers xsi:type="ecore:EClass" name="TitledView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LibToolBox" eSuperTypes="#//ToolBox">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" upperBound="-1"
        eType="#//Library" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapItemPoint" eSuperTypes="#//MapItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pos" eType="#//MapPoint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapLine" eSuperTypes="#//MapItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//MapPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ItemType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolBox" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapItem" eSuperTypes="#//Selectable"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapZone" eSuperTypes="#//MapItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//MapPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selectable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemType" eSuperTypes="#//Draggable"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyEditor" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//Selectable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Draggable"/>
  <eClassifiers xsi:type="ecore:EClass" name="DragTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChatPanel" eSuperTypes="#//View"/>
</ecore:EPackage>
