<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_gKn3QZiiEd63G99tGYHhbQ"
    name="sm_mm" nsURI="http://big.tuwien.ac.at/smartmatcher/ui/gmf/sm_mm1" nsPrefix="sm_mm">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_xa5FMJiiEd63G99tGYHhbQ" name="MappingModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#_kdrycJijEd63G99tGYHhbQ" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
        eType="#_EV-kQJilEd63G99tGYHhbQ" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_kdrycJijEd63G99tGYHhbQ" name="Class"
      eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_w0YpYJijEd63G99tGYHhbQ"
        name="attributes" upperBound="-1" eType="#_nqqr0JijEd63G99tGYHhbQ" containment="true"
        eOpposite="#//Attribute/container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" upperBound="-1"
        eType="#_kdrycJijEd63G99tGYHhbQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_nqqr0JijEd63G99tGYHhbQ" name="Attribute"
      eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_OfSzEJikEd63G99tGYHhbQ"
        name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#_kdrycJijEd63G99tGYHhbQ" eOpposite="#_w0YpYJijEd63G99tGYHhbQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_EV-kQJilEd63G99tGYHhbQ" name="Operator"
      abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_KkQrcJilEd63G99tGYHhbQ"
        name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//ContextOperator" eOpposite="#//ContextOperator/contextMappings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsRoles" lowerBound="1"
        upperBound="-1" eType="#//Element" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsRoles" lowerBound="1"
        upperBound="-1" eType="#//Element" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="2" upperBound="-1"
        eType="#//Element" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C2C" eSuperTypes="#//ContextOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#_kdrycJijEd63G99tGYHhbQ">
      <eAnnotations source="role">
        <details key="rolename" value="lhsFocusElement"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#_kdrycJijEd63G99tGYHhbQ">
      <eAnnotations source="role">
        <details key="rolename" value="rhsFocusElement"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A2A" eSuperTypes="#_EV-kQJilEd63G99tGYHhbQ">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#_nqqr0JijEd63G99tGYHhbQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#_nqqr0JijEd63G99tGYHhbQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#_kdrycJijEd63G99tGYHhbQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#_kdrycJijEd63G99tGYHhbQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R2R" eSuperTypes="#_EV-kQJilEd63G99tGYHhbQ">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A2C" eSuperTypes="#//ContextOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsAttribute" lowerBound="1"
        eType="#_nqqr0JijEd63G99tGYHhbQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsClass" lowerBound="1"
        eType="#_kdrycJijEd63G99tGYHhbQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsReference" lowerBound="1"
        eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsAttribute" lowerBound="1"
        eType="#_nqqr0JijEd63G99tGYHhbQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lhs" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rhs" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="false"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextOperator" abstract="true" eSuperTypes="#_EV-kQJilEd63G99tGYHhbQ">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextMappings" upperBound="-1"
        eType="#_EV-kQJilEd63G99tGYHhbQ" eOpposite="#//Operator/parents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R2A" eSuperTypes="#_EV-kQJilEd63G99tGYHhbQ">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsReference" lowerBound="1"
        eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsAttribute1" lowerBound="1"
        eType="#_nqqr0JijEd63G99tGYHhbQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsAttribute2" lowerBound="1"
        eType="#_nqqr0JijEd63G99tGYHhbQ"/>
  </eClassifiers>
</ecore:EPackage>
