<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solver"
    nsURI="http://org/eclipse/stem/core/solver" nsPrefix="org.eclipse.stem.core.solver">
  <eClassifiers xsi:type="ecore:EClass" name="Solver" eSuperTypes="common.ecore#//Identifiable">
    <eOperations name="step" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="time" eType="ecore:EClass model.ecore#//STEMTime"/>
      <eParameters name="timeDelta" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ELong"/>
      <eParameters name="cycle" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="reset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decorators" transient="true">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass model.ecore#//Decorator"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialized" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
