<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visualeditor">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//DiagramProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedNamedElement" eSuperTypes="#//NamedElement">
    <eOperations name="getFullyQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractArtifact" eSuperTypes="#//QualifiedNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//AbstractArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManagedEntityArtifact" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeArtifact" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotificationArtifact" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedQueryArtifact" eSuperTypes="#//AbstractArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnedType" eType="#//AbstractArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//AbstractArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateProcedureArtifact" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionArtifact" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="SessionFacadeArtifact" eSuperTypes="#//AbstractArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedEntities" upperBound="-1"
        eType="#//ManagedEntityArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emittedNotifications" upperBound="-1"
        eType="#//NotificationArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedQueries" upperBound="-1"
        eType="#//NamedQueryArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedProcedures" upperBound="-1"
        eType="#//UpdateProcedureArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//QualifiedNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aEnd" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndIsNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndIsOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndIsUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndIsChangeable" eType="#//ChangeableEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndAggregation" eType="#//AggregationEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zEnd" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndIsNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndIsOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndIsUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndIsChangeable" eType="#//ChangeableEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndAggregation" eType="#//AggregationEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndVisibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndVisibility" eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationClass" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedClass" eType="#//AssociationClassClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationEnum">
    <eLiterals name="none"/>
    <eLiterals name="shared" value="1"/>
    <eLiterals name="composite" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeableEnum">
    <eLiterals name="none"/>
    <eLiterals name="frozen" value="1"/>
    <eLiterals name="addOnly" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssocMultiplicity">
    <eLiterals name="ONE" literal="1"/>
    <eLiterals name="ZERO" value="1" literal="0"/>
    <eLiterals name="ZERO_ONE" value="2" literal="0..1"/>
    <eLiterals name="ZERO_STAR" value="3" literal="0..*"/>
    <eLiterals name="ONE_STAR" value="4" literal="1..*"/>
    <eLiterals name="STAR" value="5" literal="*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeMultiplicity">
    <eLiterals name="NONE" literal=""/>
    <eLiterals name="ARRAY" value="1" literal="[]"/>
    <eLiterals name="ARRAYOFARRAY" value="2" literal="[][]"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//TypeMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//AbstractArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//DiagramProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//TypeMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zEnd" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//QualifiedNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aEnd" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEndIsNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zEnd" eType="#//AbstractArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndMultiplicity" eType="#//AssocMultiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zEndIsNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationClassClass" eSuperTypes="#//AbstractArtifact"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PROTECTED" value="1"/>
    <eLiterals name="PRIVATE" value="2"/>
    <eLiterals name="PACKAGE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
