<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ucmmodel"
    nsURI="http:///org/isistan/flabot/edit/ucmmodel.ecore" nsPrefix="org.isistan.flabot.edit.ucmmodel">
  <eClassifiers xsi:type="ecore:EClass" name="UCMDiagram" eSuperTypes="editormodel.ecore#//Diagram #//Adapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" eType="ecore:EClass coremodel.ecore#//UseCaseMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter" instanceClassName="org.eclipse.emf.common.notify.Adapter"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Notifier" instanceClassName="org.eclipse.emf.common.notify.Notifier"/>
</ecore:EPackage>
