<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uForth" nsURI="urn:es.um.ssdd.uForth" nsPrefix="es.um.ssdd.uForth">
  <eClassifiers xsi:type="ecore:EClass" name="uFProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" upperBound="-1"
        eType="#//Word" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//Definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Word"/>
  <eClassifiers xsi:type="ecore:EClass" name="Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" lowerBound="1" upperBound="-1"
        eType="#//Word" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainId" eSuperTypes="#//Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
