<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visualligence" nsURI="http://www.visualligence.com/vml" nsPrefix="vml">
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Input" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
        upperBound="-1" eType="#//Output" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" ordered="false"
        upperBound="-1" eType="#//ModuleInstances" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" ordered="false"
        upperBound="-1" eType="#//TypeDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInstances" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="desc" ordered="false" lowerBound="1"
        eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" upperBound="-1" eType="#//Stream"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDecl" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NativeType" eSuperTypes="#//TypeDecl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//NativeTypeOptions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NativeTypeOptions">
    <eLiterals name="string"/>
    <eLiterals name="number"/>
    <eLiterals name="bool"/>
    <eLiterals name="color"/>
    <eLiterals name="position"/>
    <eLiterals name="angle"/>
    <eLiterals name="size"/>
    <eLiterals name="texture"/>
    <eLiterals name="value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//TypeDecl #//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//TypeDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hash" eSuperTypes="#//TypeDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//HashItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HashItem" eSuperTypes="#//NamedElement #//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stream" eSuperTypes="#//TypedElement #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Stream">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Stream"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Stream">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" ordered="false" eType="#//Stream"/>
  </eClassifiers>
</ecore:EPackage>
