<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="zoo"
    nsURI="http://modeling.eclipse.org/demo/zoo" nsPrefix="zoo">
  <eClassifiers xsi:type="ecore:EClass" name="Zoo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plots" upperBound="-1"
        eType="#//Ground" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ground" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Savannah" eSuperTypes="#//Ground">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tigers" upperBound="-1"
        eType="#//Tiger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Water" eSuperTypes="#//Ground">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fishes" upperBound="-1"
        eType="#//Fish" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Walkway" eSuperTypes="#//Ground">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visitors" upperBound="-1"
        eType="#//Visitor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Animal" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visitor" eSuperTypes="#//Animal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tiger" eSuperTypes="#//Animal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fish" eSuperTypes="#//Animal"/>
</ecore:EPackage>
