<?xml version="1.0" encoding="ISO-8859-1"?>
<Metamodel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="KM3" location="1:1-60:2">
  <contents location="1:1-60:2" name="Sample">
    <contents xsi:type="Class" location="2:9-8:10" name="Person" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="3:17-3:49" name="name_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Reference" location="4:17-4:50" name="address" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.7" isContainer="false"/>
      <structuralFeatures xsi:type="Attribute" location="5:17-5:52" name="works_for" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.2"/>
      <structuralFeatures xsi:type="Reference" location="6:17-6:52" name="performsTask" lower="1" upper="1" isOrdered="false" type="//@contents.0/@contents.8" isContainer="false"/>
      <structuralFeatures xsi:type="Attribute" location="7:17-7:47" name="persistent" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="Class" location="10:9-13:10" name="Student" isAbstract="false" supertypes="//@contents.0/@contents.0">
      <structuralFeatures xsi:type="Attribute" location="11:17-11:50" name="studiesIn" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.3"/>
      <structuralFeatures xsi:type="Attribute" location="12:17-12:47" name="supervisor" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.0"/>
    </contents>
    <contents xsi:type="Class" location="15:9-19:10" name="Organization" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="16:13-16:45" name="name_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Attribute" location="17:13-17:41" name="address" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.7"/>
      <structuralFeatures xsi:type="Attribute" location="18:13-18:43" name="persistent" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="Class" location="21:9-23:10" name="University" isAbstract="false" supertypes="//@contents.0/@contents.2">
      <structuralFeatures xsi:type="Attribute" location="22:17-22:45" name="faculty" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.6"/>
    </contents>
    <contents xsi:type="Class" location="25:9-27:10" name="Company" isAbstract="false" supertypes="//@contents.0/@contents.2">
      <structuralFeatures xsi:type="Attribute" location="26:17-26:44" name="manager" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.0"/>
    </contents>
    <contents xsi:type="Class" location="29:9-31:10" name="AcademicInstitution" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="30:17-30:49" name="name_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="Class" location="33:9-36:10" name="Faculty" isAbstract="false" supertypes="//@contents.0/@contents.5">
      <structuralFeatures xsi:type="Attribute" location="34:17-34:45" name="address" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.7"/>
      <structuralFeatures xsi:type="Attribute" location="35:17-35:41" name="dean" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.0"/>
    </contents>
    <contents xsi:type="Class" location="38:9-42:10" name="Address" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="39:13-39:37" name="city" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Attribute" location="40:13-40:39" name="street" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Attribute" location="41:13-41:41" name="postcode" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="Class" location="44:9-49:10" name="Task" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="45:17-45:49" name="name_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Attribute" location="46:17-46:52" name="number_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.11"/>
      <structuralFeatures xsi:type="Attribute" location="47:17-47:50" name="description" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.9"/>
      <structuralFeatures xsi:type="Attribute" location="48:17-48:47" name="persistent" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="Class" location="51:9-56:10" name="Document" isAbstract="false">
      <structuralFeatures xsi:type="Attribute" location="52:17-52:52" name="number_primary" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.11"/>
      <structuralFeatures xsi:type="Attribute" location="53:17-53:43" name="author" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.0"/>
      <structuralFeatures xsi:type="Attribute" location="54:17-54:44" name="content" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
      <structuralFeatures xsi:type="Attribute" location="55:17-55:47" name="persistent" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.10"/>
    </contents>
    <contents xsi:type="DataType" location="58:9-58:25" name="String"/>
    <contents xsi:type="DataType" location="59:9-59:26" name="Integer"/>
  </contents>
</Metamodel>
